Brand.delete_all
acquadiparma=Brand.create("name" => "Acqua Di Parma")
agave=Brand.create("name" => "Agave")
algenist=Brand.create("name" => "Algenist")
alterna=Brand.create("name" => "ALTERNA")
amazingcosmetics=Brand.create("name" => "Amazing Cosmetics")
amika=Brand.create("name" => "Amika")
amorepacific=Brand.create("name" => "AmorePacific")
anastasiabeverlyhills=Brand.create("name" => "Anastasia Beverly Hills")
annasui=Brand.create("name" => "Anna Sui")
anthonylogisticsformen=Brand.create("name" => "Anthony Logistics For Men")
apivita=Brand.create("name" => "Apivita")
ardencyinn=Brand.create("name" => "ARDENCY INN")
theartofshaving=Brand.create("name" => "The Art of Shaving")
ateliercologne=Brand.create("name" => "Atelier Cologne")
balenciaga=Brand.create("name" => "BALENCIAGA")
bareminerals=Brand.create("name" => "bareMinerals")
beautyblender=Brand.create("name" => "beautyblender")
becca=Brand.create("name" => "BECCA")
benefitcosmetics=Brand.create("name" => "Benefit Cosmetics")
bitebeauty=Brand.create("name" => "Bite Beauty")
blinc=Brand.create("name" => "Blinc")
bliss=Brand.create("name" => "Bliss")
bobbibrown=Brand.create("name" => "Bobbi Brown")
boscia=Brand.create("name" => "boscia")
boyfriend=Brand.create("name" => "Boyfriend")
brazilianpeel=Brand.create("name" => "Brazilian Peel")
bronzebuffer=Brand.create("name" => "Bronze Buffer")
bumbleandbumble=Brand.create("name" => "Bumble and bumble")
burberry=Brand.create("name" => "Burberry")
butterlondon=Brand.create("name" => "butter LONDON")
buxom=Brand.create("name" => "Buxom")
bvlgari=Brand.create("name" => "Bvlgari")
calistatools=Brand.create("name" => "Calista Tools")
calvinklein=Brand.create("name" => "Calvin Klein")
carolsdaughter=Brand.create("name" => "Carol's Daughter")
carolinaherrera=Brand.create("name" => "Carolina Herrera")
cartier=Brand.create("name" => "Cartier")
caudalie=Brand.create("name" => "Caudalie")
chanel=Brand.create("name" => "CHANEL")
charlotteronson=Brand.create("name" => "Charlotte Ronson")
chloe=Brand.create("name" => "Chloe")
ciate=Brand.create("name" => "Ciaté")
clarins=Brand.create("name" => "Clarins")
clarisonic=Brand.create("name" => "Clarisonic")
clean=Brand.create("name" => "CLEAN")
clearogen=Brand.create("name" => "Clearogen")
clinique=Brand.create("name" => "CLINIQUE")
coach=Brand.create("name" => "COACH")
colorsmash=Brand.create("name" => "Colorsmash")
comptoirsudpacifique=Brand.create("name" => "Comptoir Sud Pacifique")
couturecolour=Brand.create("name" => "Couture Colour")
coverfx=Brand.create("name" => "COVER FX")
curlstyler=Brand.create("name" => "Curl Styler")
dg=Brand.create("name" => "D&G")
ddf=Brand.create("name" => "DDF")
deborahlippmann=Brand.create("name" => "Deborah Lippmann")
dermadoctor=Brand.create("name" => "DERMAdoctor")
desigual=Brand.create("name" => "DESIGUAL")
devacurl=Brand.create("name" => "DevaCurl")
diamancel=Brand.create("name" => "Diamancel")
dianevonfurstenberg=Brand.create("name" => "Diane von Furstenberg")
diesel=Brand.create("name" => "Diesel")
dior=Brand.create("name" => "Dior")
disneycollection=Brand.create("name" => "Disney Collection")
divergentcosmetics=Brand.create("name" => "Divergent Cosmetics")
dkny=Brand.create("name" => "DKNY")
dolce&gabbana=Brand.create("name" => "Dolce & Gabbana")
donnakaran=Brand.create("name" => "Donna Karan")
drbrandtskincare=Brand.create("name" => "Dr. Brandt Skincare")
drdennisgrossskincare=Brand.create("name" => "Dr. Dennis Gross Skincare")
drjart=Brand.create("name" => "Dr. Jart+")
drlipp=Brand.create("name" => "Dr. Lipp")
drybar=Brand.create("name" => "Drybar")
duo=Brand.create("name" => "DUO")
edwardbess=Brand.create("name" => "EDWARD BESS")
elizabethandjames=Brand.create("name" => "Elizabeth and James")
ellisfaas=Brand.create("name" => "ELLIS FAAS")
escada=Brand.create("name" => "Escada")
esteelauder=Brand.create("name" => "Estee Lauder")
evelom=Brand.create("name" => "Eve Lom")
evian=Brand.create("name" => "Evian")
eyeko=Brand.create("name" => "Eyeko")
fendi=Brand.create("name" => "Fendi")
firstaidbeauty=Brand.create("name" => "First Aid Beauty")
foreo=Brand.create("name" => "Foreo")
formulax=Brand.create("name" => "Formula X")
fresh=Brand.create("name" => "Fresh")
ghd=Brand.create("name" => "ghd")
giorgioarmani=Brand.create("name" => "Giorgio Armani")
givenchy=Brand.create("name" => "Givenchy")
glamglow=Brand.create("name" => "GLAMGLOW")
glo=Brand.create("name" => "GLO")
gucci=Brand.create("name" => "Gucci")
guerlain=Brand.create("name" => "Guerlain")
hairmax=Brand.create("name" => "HairMax")
hamptonsun=Brand.create("name" => "Hampton Sun")
hanaemori=Brand.create("name" => "Hanae Mori")
harajukulovers=Brand.create("name" => "Harajuku Lovers")
hellokitty=Brand.create("name" => "Hello Kitty")
hermes=Brand.create("name" => "HERMÈS")
hourglass=Brand.create("name" => "Hourglass")
hugoboss=Brand.create("name" => "Hugo Boss")
ilovenewyorkbybondno9=Brand.create("name" => "I LOVE NEW YORK by Bond No. 9")
illamasqua=Brand.create("name" => "Illamasqua")
isseymiyake=Brand.create("name" => "Issey Miyake")
jackblack=Brand.create("name" => "Jack Black")
jeanpaulgaultier=Brand.create("name" => "Jean Paul Gaultier")
jenniferaniston=Brand.create("name" => "Jennifer Aniston")
jimmychoo=Brand.create("name" => "JIMMY CHOO")
jinsoon=Brand.create("name" => "JINsoon")
johnvarvatos=Brand.create("name" => "John Varvatos")
josiemaran=Brand.create("name" => "Josie Maran")
juicycouture=Brand.create("name" => "Juicy Couture")
julep=Brand.create("name" => "Julep")
jurlique=Brand.create("name" => "Jurlique")
karuna=Brand.create("name" => "Karuna")
katvond=Brand.create("name" => "Kat Von D")
katesomerville=Brand.create("name" => "Kate Somerville")
kenzo=Brand.create("name" => "Kenzo")
keratinperfect=Brand.create("name" => "KeratinPerfect")
kohgendo=Brand.create("name" => "Koh Gen Do")
korres=Brand.create("name" => "Korres")
lartisanparfumeur=Brand.create("name" => "L'Artisan Parfumeur")
loccitane=Brand.create("name" => "L'Occitane")
labseriesformen=Brand.create("name" => "Lab Series For Men")
lacoste=Brand.create("name" => "Lacoste")
lancome=Brand.create("name" => "Lancôme")
lashfood=Brand.create("name" => "LASHFOOD")
lauramercier=Brand.create("name" => "Laura Mercier")
lavanila=Brand.create("name" => "LAVANILA")
leajourno=Brand.create("name" => "Lea Journo")
litcosmetics=Brand.create("name" => "Lit Cosmetics")
livingproof=Brand.create("name" => "Living Proof")
lorac=Brand.create("name" => "LORAC")
maisonmartinmargiela=Brand.create("name" => "MAISON MARTIN MARGIELA")
makeupforever=Brand.create("name" => "MAKE UP FOR EVER")
manukadoctor=Brand.create("name" => "Manuka Doctor")
marcjacobsbeauty=Brand.create("name" => "Marc Jacobs Beauty")
marcjacobsfragrance=Brand.create("name" => "Marc Jacobs Fragrance")
marchesa=Brand.create("name" => "MARCHESA")
marula=Brand.create("name" => "Marula")
masqueology=Brand.create("name" => "Masque*ology")
mdsolarsciences=Brand.create("name" => "MDSolarSciences")
mesmooth=Brand.create("name" => "me smooth")
michaelkors=Brand.create("name" => "Michael Kors")
montblanc=Brand.create("name" => "Montblanc")
murad=Brand.create("name" => "Murad")
mustela=Brand.create("name" => "Mustela")
nailsinc=Brand.create("name" => "nails inc.")
narcisorodriguez=Brand.create("name" => "Narciso Rodriguez")
nars=Brand.create("name" => "NARS")
nest=Brand.create("name" => "NEST")
thenewblack=Brand.create("name" => "The New Black")
nobleedinglips=Brand.create("name" => "No Bleeding Lips")
nubrilliance=Brand.create("name" => "Nu Brilliance")
nudeskincare=Brand.create("name" => "NUDE Skincare")
nuface=Brand.create("name" => "NuFACE")
obsessivecompulsivecosmetics=Brand.create("name" => "Obsessive Compulsive Cosmetics")
ojon=Brand.create("name" => "Ojon")
olehenriksen=Brand.create("name" => "Ole Henriksen")
omorovicza=Brand.create("name" => "Omorovicza")
onedirection=Brand.create("name" => "One Direction")
origins=Brand.create("name" => "Origins")
oscarblandi=Brand.create("name" => "Oscar Blandi")
ouidad=Brand.create("name" => "Ouidad")
pacorabanne=Brand.create("name" => "Paco Rabanne")
perfectformula=Brand.create("name" => "Perfect Formula")
perfekt=Brand.create("name" => "Perfekt")
perriconemd=Brand.create("name" => "Perricone MD")
peterthomasroth=Brand.create("name" => "Peter Thomas Roth")
philosophy=Brand.create("name" => "Philosophy")
phyto=Brand.create("name" => "Phyto")
pinchprovisions=Brand.create("name" => "Pinch Provisions")
pinksugar=Brand.create("name" => "Pink Sugar")
prada=Brand.create("name" => "Prada")
radicalskincare=Brand.create("name" => "Radical Skincare")
ralphlauren=Brand.create("name" => "Ralph Lauren")
ren=Brand.create("name" => "REN")
riiviva=Brand.create("name" => "Riiviva")
ritahazan=Brand.create("name" => "Rita Hazan")
rosebudperfumeco=Brand.create("name" => "Rosebud Perfume Co.")
sachajuan=Brand.create("name" => "Sachajuan")
sephorabyopi=Brand.create("name" => "SEPHORA by OPI")
sephoracollection=Brand.create("name" => "SEPHORA COLLECTION")
sephorafavorites=Brand.create("name" => "Sephora Favorites")
sephorapantoneuniverse=Brand.create("name" => "SEPHORA+PANTONE UNIVERSE")
shaveworks=Brand.create("name" => "Shaveworks")
shiseido=Brand.create("name" => "Shiseido")
silkn=Brand.create("name" => "Silk'n")
skii=Brand.create("name" => "SK-II")
smashbox=Brand.create("name" => "Smashbox")
soap&glory=Brand.create("name" => "Soap & Glory")
sponge=Brand.create("name" => "Sponge")
sttropeztanningessentials=Brand.create("name" => "St. Tropez Tanning Essentials")
stellamccartney=Brand.create("name" => "Stella McCartney")
stila=Brand.create("name" => "Stila")
sultra=Brand.create("name" => "Sultra")
sundayriley=Brand.create("name" => "Sunday Riley")
supergoop=Brand.create("name" => "Supergoop!")
t3=Brand.create("name" => "T3")
tanda=Brand.create("name" => "Tanda")
tangleteezer=Brand.create("name" => "Tangle Teezer")
tantowel=Brand.create("name" => "TanTowel")
tarte=Brand.create("name" => "Tarte")
tataharper=Brand.create("name" => "Tata Harper")
tatcha=Brand.create("name" => "Tatcha")
tenoverten=Brand.create("name" => "tenoverten")
thebalm=Brand.create("name" => "TheBalm")
thierrymugler=Brand.create("name" => "Thierry Mugler")
toccabeauty=Brand.create("name" => "Tocca Beauty")
tokyomilkdark=Brand.create("name" => "TokyoMilk Dark")
tomford=Brand.create("name" => "TOM FORD")
toofaced=Brand.create("name" => "Too Faced")
toppik=Brand.create("name" => "Toppik")
toryburch=Brand.create("name" => "Tory Burch")
tria=Brand.create("name" => "Tria")
tweezerman=Brand.create("name" => "Tweezerman")
urbandecay=Brand.create("name" => "Urban Decay")
valuesinsideout=Brand.create("name" => "Values Inside Out")
versace=Brand.create("name" => "Versace")
versoskincare=Brand.create("name" => "VERSO SKINCARE")
viktor&rolf=Brand.create("name" => "Viktor & Rolf")
vitaliberata=Brand.create("name" => "Vita Liberata")
wei=Brand.create("name" => "Wei")
wenbychazdean=Brand.create("name" => "WEN® by Chaz Dean")
whenbrand=Brand.create("name" => "When")
21drops=Brand.create("name" => "21 Drops")

Category.delete_all
cleanser=Category.create("name" => "Cleanser")
moisturizer=Category.create("name" => "Moisturizer")
treatment=Category.create("name" => "Treatment")
sunscreen=Category.create("name" => "Sunscreen")
tanning=Category.create("name" => "Tanning")
other=Category.create("name" => "Other")

SkinType.delete_all
dry=SkinType.create("name" => "Dry")
oily=SkinType.create("name" => "Oily")
combo=SkinType.create("name" => "Combination")
normal=SkinType.create("name" => "Normal")

ProductType.delete_all
facewash_cleanser=Producttype.create("category_id" => "cleanser.id", "name" => "Face Wash & Cleanser")
exfoliators=Producttype.create("category_id" => "cleanser.id", "name" => "Exfoliators")
toners=Producttype.create("category_id" => "cleanser.id", "name" => "Toners")
makeup_remover=Producttype.create("category_id" => "cleanser.id", "name" => "Makeup Remover")
cleansing_brushes_tools=Producttype.create("category_id" => "cleanser.id", "name" => "Cleansing Brushes & Tools")
moisturizer=Producttype.create("category_id" => "moisturizer.id", "name" => "Moisturizer")
night_cream=Producttype.create("category_id" => "moisturizer.id", "name" => "Night Cream")
bbcream_cccream=Producttype.create("category_id" => "moisturizer.id", "name" => "BB Cream & CC Cream")
tinted_moisturizer=Producttype.create("category_id" => "moisturizer.id", "name" => "Tinted Moisturizer")
face_oil=Producttype.create("category_id" => "moisturizer.id", "name" => "Face Oil")
face_mist=Producttype.create("category_id" => "moisturizer.id", "name" => "Face Mist")
eye_cream=Producttype.create("category_id" => "moisturizer.id", "name" => "Eye Cream")
decollete_neckcream=Producttype.create("category_id" => "moisturizer.id", "name" => "Decollete & Neck Cream")
lipbalm_treatments=Producttype.create("category_id" => "moisturizer.id", "name" => "Lip Balm & Treatments")
faceserum_treatments=Producttype.create("category_id" => "treatment.id", "name" => "Face Serum & Treatments")
blemish_acnetreatments=Producttype.create("category_id" => "treatment.id", "name" => "Blemish & Acne Treatments")
face_masks=Producttype.create("category_id" => "treatment.id", "name" => "Face Masks")
facial_peels=Producttype.create("category_id" => "treatment.id", "name" => "Facial Peels")
eye_treatments=Producttype.create("category_id" => "treatment.id", "name" => "Eye Treatments")
face=Producttype.create("category_id" => "sunscreen.id", "name" => "Face")
face=Producttype.create("category_id" => "tanning.id", "name" => "Face")
cellulite_stretchmarks=Producttype.create("category_id" => "other.id", "name" => "Cellulite & Stretch Marks")
hair_removal=Producttype.create("category_id" => "other.id", "name" => "Hair Removal")
teeth_whitening=Producttype.create("category_id" => "other.id", "name" => "Teeth Whitening")
mother_baby=Producttype.create("category_id" => "other.id", "name" => "Mother & Baby")
supplements=Producttype.create("category_id" => "other.id", "name" => "Supplements")
oilcontrol_blottingpaper=Producttype.create("category_id" => "other.id", "name" => "Oil Control & Blotting Paper")