Brand.delete_all
acquadiparma=Brand.create("name" => "Acqua Di Parma")
agave=Brand.create("name" => "Agave")
algenist=Brand.create("name" => "Algenist")
alterna=Brand.create("name" => "ALTERNA")
amazingcosmetics=Brand.create("name" => "Amazing Cosmetics")
amika=Brand.create("name" => "Amika")
amorepacific=Brand.create("name" => "AmorePacific")
anastasiabeverlyhills=Brand.create("name" => "Anastasia Beverly Hills")
annasui=Brand.create("name" => "Anna Sui")
anthonylogisticsformen=Brand.create("name" => "Anthony Logistics For Men")
apivita=Brand.create("name" => "Apivita")
ardencyinn=Brand.create("name" => "ARDENCY INN")
theartofshaving=Brand.create("name" => "The Art of Shaving")
ateliercologne=Brand.create("name" => "Atelier Cologne")
balenciaga=Brand.create("name" => "BALENCIAGA")
bareminerals=Brand.create("name" => "bareMinerals")
beautyblender=Brand.create("name" => "beautyblender")
becca=Brand.create("name" => "BECCA")
benefitcosmetics=Brand.create("name" => "Benefit Cosmetics")
bitebeauty=Brand.create("name" => "Bite Beauty")
blinc=Brand.create("name" => "Blinc")
bliss=Brand.create("name" => "Bliss")
bobbibrown=Brand.create("name" => "Bobbi Brown")
boscia=Brand.create("name" => "boscia")
boyfriend=Brand.create("name" => "Boyfriend")
brazilianpeel=Brand.create("name" => "Brazilian Peel")
bronzebuffer=Brand.create("name" => "Bronze Buffer")
bumbleandbumble=Brand.create("name" => "Bumble and bumble")
burberry=Brand.create("name" => "Burberry")
butterlondon=Brand.create("name" => "butter LONDON")
buxom=Brand.create("name" => "Buxom")
bvlgari=Brand.create("name" => "Bvlgari")
calistatools=Brand.create("name" => "Calista Tools")
calvinklein=Brand.create("name" => "Calvin Klein")
carolsdaughter=Brand.create("name" => "Carol's Daughter")
carolinaherrera=Brand.create("name" => "Carolina Herrera")
cartier=Brand.create("name" => "Cartier")
caudalie=Brand.create("name" => "Caudalie")
chanel=Brand.create("name" => "CHANEL")
charlotteronson=Brand.create("name" => "Charlotte Ronson")
chloe=Brand.create("name" => "Chloe")
ciate=Brand.create("name" => "Ciaté")
clarins=Brand.create("name" => "Clarins")
clarisonic=Brand.create("name" => "Clarisonic")
clean=Brand.create("name" => "CLEAN")
clearogen=Brand.create("name" => "Clearogen")
clinique=Brand.create("name" => "CLINIQUE")
coach=Brand.create("name" => "COACH")
colorsmash=Brand.create("name" => "Colorsmash")
comptoirsudpacifique=Brand.create("name" => "Comptoir Sud Pacifique")
couturecolour=Brand.create("name" => "Couture Colour")
coverfx=Brand.create("name" => "COVER FX")
curlstyler=Brand.create("name" => "Curl Styler")
dg=Brand.create("name" => "D&G")
ddf=Brand.create("name" => "DDF")
deborahlippmann=Brand.create("name" => "Deborah Lippmann")
dermadoctor=Brand.create("name" => "DERMAdoctor")
desigual=Brand.create("name" => "DESIGUAL")
devacurl=Brand.create("name" => "DevaCurl")
diamancel=Brand.create("name" => "Diamancel")
dianevonfurstenberg=Brand.create("name" => "Diane von Furstenberg")
diesel=Brand.create("name" => "Diesel")
dior=Brand.create("name" => "Dior")
disneycollection=Brand.create("name" => "Disney Collection")
divergentcosmetics=Brand.create("name" => "Divergent Cosmetics")
dkny=Brand.create("name" => "DKNY")
dolcegabbana=Brand.create("name" => "Dolce & Gabbana")
donnakaran=Brand.create("name" => "Donna Karan")
drbrandtskincare=Brand.create("name" => "Dr. Brandt Skincare")
drdennisgrossskincare=Brand.create("name" => "Dr. Dennis Gross Skincare")
drjart=Brand.create("name" => "Dr. Jart+")
drlipp=Brand.create("name" => "Dr. Lipp")
drybar=Brand.create("name" => "Drybar")
duo=Brand.create("name" => "DUO")
edwardbess=Brand.create("name" => "EDWARD BESS")
elizabethandjames=Brand.create("name" => "Elizabeth and James")
ellisfaas=Brand.create("name" => "ELLIS FAAS")
escada=Brand.create("name" => "Escada")
esteelauder=Brand.create("name" => "Estee Lauder")
evelom=Brand.create("name" => "Eve Lom")
evian=Brand.create("name" => "Evian")
eyeko=Brand.create("name" => "Eyeko")
fendi=Brand.create("name" => "Fendi")
firstaidbeauty=Brand.create("name" => "First Aid Beauty")
foreo=Brand.create("name" => "Foreo")
formulax=Brand.create("name" => "Formula X")
fresh=Brand.create("name" => "Fresh")
ghd=Brand.create("name" => "ghd")
giorgioarmani=Brand.create("name" => "Giorgio Armani")
givenchy=Brand.create("name" => "Givenchy")
glamglow=Brand.create("name" => "GLAMGLOW")
glo=Brand.create("name" => "GLO")
gucci=Brand.create("name" => "Gucci")
guerlain=Brand.create("name" => "Guerlain")
hairmax=Brand.create("name" => "HairMax")
hamptonsun=Brand.create("name" => "Hampton Sun")
hanaemori=Brand.create("name" => "Hanae Mori")
harajukulovers=Brand.create("name" => "Harajuku Lovers")
hellokitty=Brand.create("name" => "Hello Kitty")
hermes=Brand.create("name" => "HERMÈS")
hourglass=Brand.create("name" => "Hourglass")
hugoboss=Brand.create("name" => "Hugo Boss")
ilovenewyorkbybondno9=Brand.create("name" => "I LOVE NEW YORK by Bond No. 9")
illamasqua=Brand.create("name" => "Illamasqua")
isseymiyake=Brand.create("name" => "Issey Miyake")
jackblack=Brand.create("name" => "Jack Black")
jeanpaulgaultier=Brand.create("name" => "Jean Paul Gaultier")
jenniferaniston=Brand.create("name" => "Jennifer Aniston")
jimmychoo=Brand.create("name" => "JIMMY CHOO")
jinsoon=Brand.create("name" => "JINsoon")
johnvarvatos=Brand.create("name" => "John Varvatos")
josiemaran=Brand.create("name" => "Josie Maran")
juicycouture=Brand.create("name" => "Juicy Couture")
julep=Brand.create("name" => "Julep")
jurlique=Brand.create("name" => "Jurlique")
karuna=Brand.create("name" => "Karuna")
katvond=Brand.create("name" => "Kat Von D")
katesomerville=Brand.create("name" => "Kate Somerville")
kiehls=Brand.create("name" => "Kiehls")
kenzo=Brand.create("name" => "Kenzo")
keratinperfect=Brand.create("name" => "KeratinPerfect")
kohgendo=Brand.create("name" => "Koh Gen Do")
korres=Brand.create("name" => "Korres")
lartisanparfumeur=Brand.create("name" => "L'Artisan Parfumeur")
loccitane=Brand.create("name" => "L'Occitane")
labseriesformen=Brand.create("name" => "Lab Series For Men")
lacoste=Brand.create("name" => "Lacoste")
lancome=Brand.create("name" => "Lancôme")
lashfood=Brand.create("name" => "LASHFOOD")
lauramercier=Brand.create("name" => "Laura Mercier")
lavanila=Brand.create("name" => "LAVANILA")
leajourno=Brand.create("name" => "Lea Journo")
litcosmetics=Brand.create("name" => "Lit Cosmetics")
livingproof=Brand.create("name" => "Living Proof")
lorac=Brand.create("name" => "LORAC")
maisonmartinmargiela=Brand.create("name" => "MAISON MARTIN MARGIELA")
makeupforever=Brand.create("name" => "MAKE UP FOR EVER")
manukadoctor=Brand.create("name" => "Manuka Doctor")
marcjacobsbeauty=Brand.create("name" => "Marc Jacobs Beauty")
marcjacobsfragrance=Brand.create("name" => "Marc Jacobs Fragrance")
marchesa=Brand.create("name" => "MARCHESA")
marula=Brand.create("name" => "Marula")
masqueology=Brand.create("name" => "Masque*ology")
mdsolarsciences=Brand.create("name" => "MDSolarSciences")
mesmooth=Brand.create("name" => "me smooth")
michaelkors=Brand.create("name" => "Michael Kors")
montblanc=Brand.create("name" => "Montblanc")
murad=Brand.create("name" => "Murad")
mustela=Brand.create("name" => "Mustela")
nailsinc=Brand.create("name" => "nails inc.")
narcisorodriguez=Brand.create("name" => "Narciso Rodriguez")
nars=Brand.create("name" => "NARS")
nest=Brand.create("name" => "NEST")
thenewblack=Brand.create("name" => "The New Black")
nobleedinglips=Brand.create("name" => "No Bleeding Lips")
nubrilliance=Brand.create("name" => "Nu Brilliance")
nudeskincare=Brand.create("name" => "NUDE Skincare")
nuface=Brand.create("name" => "NuFACE")
obsessivecompulsivecosmetics=Brand.create("name" => "Obsessive Compulsive Cosmetics")
ojon=Brand.create("name" => "Ojon")
olehenriksen=Brand.create("name" => "Ole Henriksen")
omorovicza=Brand.create("name" => "Omorovicza")
onedirection=Brand.create("name" => "One Direction")
origins=Brand.create("name" => "Origins")
oscarblandi=Brand.create("name" => "Oscar Blandi")
ouidad=Brand.create("name" => "Ouidad")
pacorabanne=Brand.create("name" => "Paco Rabanne")
perfectformula=Brand.create("name" => "Perfect Formula")
perfekt=Brand.create("name" => "Perfekt")
perriconemd=Brand.create("name" => "Perricone MD")
peterthomasroth=Brand.create("name" => "Peter Thomas Roth")
philosophy=Brand.create("name" => "Philosophy")
phyto=Brand.create("name" => "Phyto")
pinchprovisions=Brand.create("name" => "Pinch Provisions")
pinksugar=Brand.create("name" => "Pink Sugar")
prada=Brand.create("name" => "Prada")
radicalskincare=Brand.create("name" => "Radical Skincare")
ralphlauren=Brand.create("name" => "Ralph Lauren")
ren=Brand.create("name" => "REN")
riiviva=Brand.create("name" => "Riiviva")
ritahazan=Brand.create("name" => "Rita Hazan")
rosebudperfumeco=Brand.create("name" => "Rosebud Perfume Co.")
sachajuan=Brand.create("name" => "Sachajuan")
sephorabyopi=Brand.create("name" => "SEPHORA by OPI")
sephoracollection=Brand.create("name" => "SEPHORA COLLECTION")
sephorafavorites=Brand.create("name" => "Sephora Favorites")
sephorapantoneuniverse=Brand.create("name" => "SEPHORA+PANTONE UNIVERSE")
shaveworks=Brand.create("name" => "Shaveworks")
shiseido=Brand.create("name" => "Shiseido")
silkn=Brand.create("name" => "Silk'n")
skii=Brand.create("name" => "SK-II")
smashbox=Brand.create("name" => "Smashbox")
soapglory=Brand.create("name" => "Soap & Glory")
sponge=Brand.create("name" => "Sponge")
sttropeztanningessentials=Brand.create("name" => "St. Tropez Tanning Essentials")
stellamccartney=Brand.create("name" => "Stella McCartney")
stila=Brand.create("name" => "Stila")
sultra=Brand.create("name" => "Sultra")
sundayriley=Brand.create("name" => "Sunday Riley")
supergoop=Brand.create("name" => "Supergoop!")
t3=Brand.create("name" => "T3")
tanda=Brand.create("name" => "Tanda")
tangleteezer=Brand.create("name" => "Tangle Teezer")
tantowel=Brand.create("name" => "TanTowel")
tarte=Brand.create("name" => "Tarte")
tataharper=Brand.create("name" => "Tata Harper")
tatcha=Brand.create("name" => "Tatcha")
tenoverten=Brand.create("name" => "tenoverten")
thebalm=Brand.create("name" => "TheBalm")
thierrymugler=Brand.create("name" => "Thierry Mugler")
toccabeauty=Brand.create("name" => "Tocca Beauty")
tokyomilkdark=Brand.create("name" => "TokyoMilk Dark")
tomford=Brand.create("name" => "TOM FORD")
toofaced=Brand.create("name" => "Too Faced")
toppik=Brand.create("name" => "Toppik")
toryburch=Brand.create("name" => "Tory Burch")
tria=Brand.create("name" => "Tria")
tweezerman=Brand.create("name" => "Tweezerman")
urbandecay=Brand.create("name" => "Urban Decay")
valuesinsideout=Brand.create("name" => "Values Inside Out")
versace=Brand.create("name" => "Versace")
versoskincare=Brand.create("name" => "VERSO SKINCARE")
viktorrolf=Brand.create("name" => "Viktor & Rolf")
vitaliberata=Brand.create("name" => "Vita Liberata")
wei=Brand.create("name" => "Wei")
wenbychazdean=Brand.create("name" => "WEN® by Chaz Dean")
whenbrand=Brand.create("name" => "When")
twentyone=Brand.create("name" => "21 Drops")

Category.delete_all
cleanser=Category.create("name" => "Cleanser")
moisturizer=Category.create("name" => "Moisturizer")
treatment=Category.create("name" => "Treatment")
sunscreen=Category.create("name" => "Sunscreen")
tanning=Category.create("name" => "Tanning")
other=Category.create("name" => "Other")

SkinType.delete_all
dry=SkinType.create("name" => "Dry")
oily=SkinType.create("name" => "Oily")
combo=SkinType.create("name" => "Combination")
normal=SkinType.create("name" => "Normal")

ProductType.delete_all
facewash_cleanser=ProductType.create("category_id" => cleanser.id, "name" => "Face Wash & Cleanser")
exfoliators=ProductType.create("category_id" => cleanser.id, "name" => "Exfoliators")
toners=ProductType.create("category_id" => cleanser.id, "name" => "Toners")
makeup_remover=ProductType.create("category_id" => cleanser.id, "name" => "Makeup Remover")
cleansing_brushes_tools=ProductType.create("category_id" => cleanser.id, "name" => "Cleansing Brushes & Tools")
moisturizer=ProductType.create("category_id" => moisturizer.id, "name" => "Moisturizer")
nightcream=ProductType.create("category_id" => moisturizer.id, "name" => "Night Cream")
bbcreamcccream=ProductType.create("category_id" => moisturizer.id, "name" => "BB Cream & CC Cream")
tintedmoisturizer=ProductType.create("category_id" => moisturizer.id, "name" => "Tinted Moisturizer")
faceoil=ProductType.create("category_id" => moisturizer.id, "name" => "Face Oil")
facemist=ProductType.create("category_id" => moisturizer.id, "name" => "Face Mist")
eyecream=ProductType.create("category_id" => moisturizer.id, "name" => "Eye Cream")
decolleteneckcream=ProductType.create("category_id" => moisturizer.id, "name" => "Decollete & Neck Cream")
lipbalmtreatments=ProductType.create("category_id" => moisturizer.id, "name" => "Lip Balm & Treatments")
faceserumtreatments=ProductType.create("category_id" => treatment.id, "name" => "Face Serum & Treatments")
blemishacnetreatments=ProductType.create("category_id" => treatment.id, "name" => "Blemish & Acne Treatments")
facemasks=ProductType.create("category_id" => treatment.id, "name" => "Face Masks")
facial_peels=ProductType.create("category_id" => treatment.id, "name" => "Facial Peels")
eye_treatments=ProductType.create("category_id" => treatment.id, "name" => "Eye Treatments")
facesunscreen=ProductType.create("category_id" => sunscreen.id, "name" => "Face")
facetanning=ProductType.create("category_id" => tanning.id, "name" => "Face")
cellulite_stretchmarks=ProductType.create("category_id" => other.id, "name" => "Cellulite & Stretch Marks")
hair_removal=ProductType.create("category_id" => other.id, "name" => "Hair Removal")
teeth_whitening=ProductType.create("category_id" => other.id, "name" => "Teeth Whitening")
mother_baby=ProductType.create("category_id" => other.id, "name" => "Mother & Baby")
supplements=ProductType.create("category_id" => other.id, "name" => "Supplements")
oilcontrol_blottingpaper=ProductType.create("category_id" => other.id, "name" => "Oil Control & Blotting Paper")

Product.delete_all
korresm=Product.create("brand_id" => korres.id, "product_type_id" => nightcream.id, "description" => "A weightless soufflé powered by super-charged proteins that melts into skin and works overnight for intense, immediate moisturization.", "price" => "45", "skintype_id" => combo.id, "review_count" => "318", "rating" => "4.5", "link" => "http://www.sephora.com/greek-yoghurt-advanced-nourishing-sleeping-facial-P379063?skuId=1522606", "image" => "http://www.sephora.com/productimages/sku/s1522606-main-hero.jpg")
glamglowm=Product.create("brand_id" => glamglow.id, "product_type_id" => nightcream.id, "description" => "A nondrying hydration mask to deliver instant, extreme hydration.", "price" => "69", "skintype_id" => combo.id, "review_count" => "228", "rating" => "4.3", "link" => "http://www.sephora.com/thirstymud-tm-hydrating-treatment-P384782?skuId=1582725", "image" => "http://www.sephora.com/productimages/sku/s1582725-main-hero.jpg")
originsm=Product.create("brand_id" => origins.id, "product_type_id" => nightcream.id, "description" => "A night cream so skin wakes up radiant and refreshed.", "price" => "39.5", "skintype_id" => combo.id, "review_count" => "323", "rating" => "4.4", "link" => "http://www.sephora.com/high-potency-night-a-mins-mineral-enriched-renewal-cream-P297520?skuId=1375724", "image" => "http://www.sephora.com/productimages/sku/s1375724-main-hero.jpg")
cliniquem=Product.create("brand_id" => clinique.id, "product_type_id" => moisturizer.id, "description" => "A luxurious moisturizer that promotes smooth, healthy-looking skin.", "price" => "26", "skintype_id" => combo.id, "review_count" => "355", "rating" => "3.7", "link" => "http://www.sephora.com/dramatically-different-moisturizing-lotion-P381030?skuId=1538354#BVRRWidgetID", "image" => "http://www.sephora.com/productimages/sku/s1538354-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => moisturizer.id, "description" => "A lightweight, oil-free hydrator for combination and oily skin.", "price" => "26", "skintype_id" => combo.id, "review_count" => "2043", "rating" => "4.5", "link" => "http://www.sephora.com/dramatically-different-moisturizing-gel-P122900?skuId=789727", "image" => "http://www.sephora.com/productimages/sku/s789727-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => moisturizer.id, "description" => "A refreshing cream-gel that instantly replenishes skin with 24 hours of soothing hydration.", "price" => "49.5", "skintype_id" => combo.id, "review_count" => "1831", "rating" => "4.5", "link" => "http://www.sephora.com/moisture-surge-extended-thirst-relief-P209117?skuId=1084805", "image" => "http://www.sephora.com/productimages/sku/s1084821-main-hero.jpg")
shiseidom=Product.create("brand_id" => shiseido.id, "product_type_id" => nightcream.id, "description" => "A multi-action nighttime revitalizer that counteracts signs of daytime damage.", "price" => "42.5", "skintype_id" => combo.id, "review_count" => "13", "rating" => "4.6", "link" => "http://www.sephora.com/the-skincare-night-moisture-recharge-enriched-P173638?skuId=986778", "image" => "http://www.sephora.com/productimages/sku/s986778-main-hero.jpg")
Product.create("brand_id" => josiemaran.id, "product_type_id" => faceoil.id, "description" => "A lightweight oil that can be used as a daily moisturizer or treatment for skin, hair, and nails.", "price" => "96", "skintype_id" => combo.id, "review_count" => "5143", "rating" => "4.5", "link" => "http://www.sephora.com/100-percent-pure-argan-oil-P218700?skuId=1121797", "image" => "http://www.sephora.com/productimages/sku/s1121797-main-hero.jpg")
freshm=Product.create("brand_id" => fresh.id, "product_type_id" => moisturizer.id, "description" => "A daily age-defying moisturizer formulated with Fresh’s proprietary Super 7 Complex, proven to prevent the signs of aging, provide 24 hours of significant moisture, and boost radiance.", "price" => "42", "skintype_id" => combo.id, "review_count" => "508", "rating" => "4.3", "link" => "http://www.sephora.com/lotus-youth-preserve-face-cream-with-super-7-complex-P377123?skuId=1488352", "image" => "http://www.sephora.com/productimages/sku/s1488352-main-hero.jpg")
Product.create("brand_id" => firstaidbeauty.id, "product_type_id" => moisturizer.id, "description" => "An over-the-counter, super-emollient cream with a spectacular whipped, non-greasy texture.", "price" => "28", "skintype_id" => combo.id, "review_count" => "2945", "rating" => "4.7", "link" => "http://www.sephora.com/ultra-repair-cream-P248407?skuId=1217744", "image" => "http://www.sephora.com/productimages/sku/s1217744-main-hero.jpg")
Product.create("brand_id" => olehenriksen.id, "product_type_id" => moisturizer.id, "description" => "A lightweight, silky moisturizer that nourishes skin as it gently exfoliates and fades dark spots.", "price" => "58", "skintype_id" => combo.id, "review_count" => "1030", "rating" => "4.4", "link" => "http://www.sephora.com/sheer-transformation-P42342?skuId=958611", "image" => "http://www.sephora.com/productimages/sku/s958611-main-hero.jpg")
Product.create("brand_id" => philosophy.id, "product_type_id" => moisturizer.id, "description" => "A cult-favorite moisturizer that gently hydrates, exfoliates, and protects the skin.", "price" => "67", "skintype_id" => combo.id, "review_count" => "6289", "rating" => "4", "link" => "http://www.sephora.com/hope-in-a-jar-P4633?skuId=351841", "image" => "http://www.sephora.com/productimages/sku/s1051887-main-hero.jpg")
Product.create("brand_id" => fresh.id, "product_type_id" => faceoil.id, "description" => "A soothing face oil packed with restorative omegas and seabuckthorn oil to preserve a youthful appearance.", "price" => "50", "skintype_id" => combo.id, "review_count" => "452", "rating" => "4.4", "link" => "http://www.sephora.com/seaberry-moisturizing-face-oil-P374948?skuId=1448745", "image" => "http://www.sephora.com/productimages/sku/s1448745-main-hero.jpg")
Product.create("brand_id" => jurlique.id, "product_type_id" => facemist.id, "description" => "A complexion balancing mist.", "price" => "35", "skintype_id" => combo.id, "review_count" => "148", "rating" => "4.4", "link" => "http://www.sephora.com/rosewater-balancing-mist-P224506?skuId=1430032", "image" => "http://www.sephora.com/productimages/sku/s1430032-main-hero.jpg")
Product.create("brand_id" => caudalie.id, "product_type_id" => facemist.id, "description" => "Part-toner, part-serum mist of essential oils and plant active ingredients.", "price" => "49", "skintype_id" => combo.id, "review_count" => "1706", "rating" => "4.4", "link" => "http://www.sephora.com/beauty-elixir-P6025?skuId=455774", "image" => "http://www.sephora.com/productimages/sku/s1231182-main-hero.jpg")
Product.create("brand_id" => shiseido.id, "product_type_id" => eyecream.id, "description" => "An ultrarich, age-defying cream that visibly improves the appearance of all types of eye area wrinkles.", "price" => "55", "skintype_id" => combo.id, "review_count" => "976", "rating" => "4.4", "link" => "http://www.sephora.com/benefiance-wrinkleresist24-intensive-eye-contour-cream-P173620?skuId=1408202", "image" => "http://www.sephora.com/productimages/sku/s1408202-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => eye_treatments.id, "description" => "A moisturizing eye treatment that helps minimize the look of dark circles, shadows, and puffiness.", "price" => "50", "skintype_id" => combo.id, "review_count" => "974", "rating" => "4.2", "link" => "http://www.sephora.com/all-about-eyes-rich-P174502?skuId=971473", "image" => "http://www.sephora.com/productimages/sku/s971473-main-hero.jpg")
Product.create("brand_id" => philosophy.id, "product_type_id" => moisturizer.id, "description" => "A rejuvenating, age-fighting hydrator that softens, firms, and brightens the complexion.", "price" => "96", "skintype_id" => combo.id, "review_count" => "1029", "rating" => "4.4", "link" => "http://www.sephora.com/miracle-worker-miraculous-anti-aging-moisturizer-P254209?skuId=1229442", "image" => "http://www.sephora.com/productimages/sku/s1229442-main-hero.jpg")
Product.create("brand_id" => josiemaran.id, "product_type_id" => faceoil.id, "description" => "An ultralightweight, quick-absorbing version of Josie’s cult-favorite 100% Pure Argan Oil.", "price" => "48", "skintype_id" => combo.id, "review_count" => "534", "rating" => "4.4", "link" => "http://www.sephora.com/100-pure-argan-oil-light-P380805?skuId=1548270", "image" => "http://www.sephora.com/productimages/sku/s1548288-main-hero.jpg")
Product.create("brand_id" => jackblack.id, "product_type_id" => lipbalmtreatments.id, "description" => "A hydrating lip balm to soothe lips while it protects from sun and wind.", "price" => "7.5", "skintype_id" => combo.id, "review_count" => "1838", "rating" => "4.7", "link" => "http://www.sephora.com/intense-therapy-lip-balm-spf-25-P12573?skuId=564344", "image" => "http://www.sephora.com/productimages/sku/s564344-main-hero.jpg")
Product.create("brand_id" => kiehls.id, "product_type_id" => moisturizer.id, "description" => "A 24-hour daily face moisturizer.", "price" => "46.5", "skintype_id" => combo.id, "review_count" => "236", "rating" => "4.8", "link" => "http://www.kiehls.com/Ultra-Facial-Cream/622,default,pd.html?start=1&cgid=face-moisturizers", "image" => "http://www.sephora.com/productimages/sku/s1408202-main-hero.jpg")

ProductRating.delete_all
ProductRating.create("user_id" => "1", "product_id" => korresm.id, "currently_use" => "1", "works" => "1", "oily" => "0", "dry" => "0", "heavy" => "0", "breakout" => "0", "allergic" => "0", "treats" => "1", "review" => "Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.", "rating" => "4")
ProductRating.create("user_id" => "1", "product_id" => glamglowm.id, "currently_use" => "0", "works" => "1", "oily" => "0", "dry" => "1", "heavy" => "0", "breakout" => "0", "allergic" => "0", "treats" => "0", "review" => "Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.", "rating" => "2")
ProductRating.create("user_id" => "1", "product_id" => originsm.id, "currently_use" => "1", "works" => "0", "oily" => "1", "dry" => "1", "heavy" => "0", "breakout" => "0", "allergic" => "0", "treats" => "0", "review" => "Maecenas sed diam eget risus varius blandit sit amet non magna.", "rating" => "3")
ProductRating.create("user_id" => "1", "product_id" => cliniquem.id, "currently_use" => "0", "works" => "0", "oily" => "0", "dry" => "1", "heavy" => "1", "breakout" => "1", "allergic" => "0", "treats" => "0", "review" => "Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.", "rating" => "1")
ProductRating.create("user_id" => "1", "product_id" => shiseidom.id, "currently_use" => "1", "works" => "1", "oily" => "1", "dry" => "0", "heavy" => "0", "breakout" => "0", "allergic" => "0", "treats" => "0", "review" => "Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.", "rating" => "5")
ProductRating.create("user_id" => "1", "product_id" => freshm.id, "currently_use" => "0", "works" => "0", "oily" => "0", "dry" => "0", "heavy" => "1", "breakout" => "1", "allergic" => "1", "treats" => "0", "review" => "Maecenas sed diam eget risus varius blandit sit amet non magna.", "rating" => "2")
