Brand.delete_all
acquadiparma=Brand.create("name" => "Acqua Di Parma")
agave=Brand.create("name" => "Agave")
algenist=Brand.create("name" => "Algenist")
alterna=Brand.create("name" => "ALTERNA")
amazingcosmetics=Brand.create("name" => "Amazing Cosmetics")
amika=Brand.create("name" => "Amika")
amorepacific=Brand.create("name" => "AmorePacific")
anastasiabeverlyhills=Brand.create("name" => "Anastasia Beverly Hills")
annasui=Brand.create("name" => "Anna Sui")
anthonylogisticsformen=Brand.create("name" => "Anthony Logistics For Men")
apivita=Brand.create("name" => "Apivita")
ardencyinn=Brand.create("name" => "ARDENCY INN")
theartofshaving=Brand.create("name" => "The Art of Shaving")
ateliercologne=Brand.create("name" => "Atelier Cologne")
balenciaga=Brand.create("name" => "BALENCIAGA")
bareminerals=Brand.create("name" => "bareMinerals")
beautyblender=Brand.create("name" => "beautyblender")
becca=Brand.create("name" => "BECCA")
benefitcosmetics=Brand.create("name" => "Benefit Cosmetics")
bitebeauty=Brand.create("name" => "Bite Beauty")
blinc=Brand.create("name" => "Blinc")
bliss=Brand.create("name" => "Bliss")
bobbibrown=Brand.create("name" => "Bobbi Brown")
boscia=Brand.create("name" => "boscia")
boyfriend=Brand.create("name" => "Boyfriend")
brazilianpeel=Brand.create("name" => "Brazilian Peel")
bronzebuffer=Brand.create("name" => "Bronze Buffer")
bumbleandbumble=Brand.create("name" => "Bumble and bumble")
burberry=Brand.create("name" => "Burberry")
butterlondon=Brand.create("name" => "butter LONDON")
buxom=Brand.create("name" => "Buxom")
bvlgari=Brand.create("name" => "Bvlgari")
calistatools=Brand.create("name" => "Calista Tools")
calvinklein=Brand.create("name" => "Calvin Klein")
carolsdaughter=Brand.create("name" => "Carol's Daughter")
carolinaherrera=Brand.create("name" => "Carolina Herrera")
cartier=Brand.create("name" => "Cartier")
caudalie=Brand.create("name" => "Caudalie")
chanel=Brand.create("name" => "CHANEL")
charlotteronson=Brand.create("name" => "Charlotte Ronson")
chloe=Brand.create("name" => "Chloe")
ciate=Brand.create("name" => "Ciaté")
clarins=Brand.create("name" => "Clarins")
clarisonic=Brand.create("name" => "Clarisonic")
clean=Brand.create("name" => "CLEAN")
clearogen=Brand.create("name" => "Clearogen")
clinique=Brand.create("name" => "CLINIQUE")
coach=Brand.create("name" => "COACH")
colorsmash=Brand.create("name" => "Colorsmash")
comptoirsudpacifique=Brand.create("name" => "Comptoir Sud Pacifique")
couturecolour=Brand.create("name" => "Couture Colour")
coverfx=Brand.create("name" => "COVER FX")
curlstyler=Brand.create("name" => "Curl Styler")
dg=Brand.create("name" => "D&G")
ddf=Brand.create("name" => "DDF")
deborahlippmann=Brand.create("name" => "Deborah Lippmann")
dermadoctor=Brand.create("name" => "DERMAdoctor")
desigual=Brand.create("name" => "DESIGUAL")
devacurl=Brand.create("name" => "DevaCurl")
diamancel=Brand.create("name" => "Diamancel")
dianevonfurstenberg=Brand.create("name" => "Diane von Furstenberg")
diesel=Brand.create("name" => "Diesel")
dior=Brand.create("name" => "Dior")
disneycollection=Brand.create("name" => "Disney Collection")
divergentcosmetics=Brand.create("name" => "Divergent Cosmetics")
dkny=Brand.create("name" => "DKNY")
dolcegabbana=Brand.create("name" => "Dolce & Gabbana")
donnakaran=Brand.create("name" => "Donna Karan")
drbrandtskincare=Brand.create("name" => "Dr. Brandt Skincare")
drdennisgrossskincare=Brand.create("name" => "Dr. Dennis Gross Skincare")
drjart=Brand.create("name" => "Dr. Jart+")
drlipp=Brand.create("name" => "Dr. Lipp")
drybar=Brand.create("name" => "Drybar")
duo=Brand.create("name" => "DUO")
edwardbess=Brand.create("name" => "EDWARD BESS")
elizabethandjames=Brand.create("name" => "Elizabeth and James")
ellisfaas=Brand.create("name" => "ELLIS FAAS")
escada=Brand.create("name" => "Escada")
esteelauder=Brand.create("name" => "Estee Lauder")
evelom=Brand.create("name" => "Eve Lom")
evian=Brand.create("name" => "Evian")
eyeko=Brand.create("name" => "Eyeko")
fendi=Brand.create("name" => "Fendi")
firstaidbeauty=Brand.create("name" => "First Aid Beauty")
foreo=Brand.create("name" => "Foreo")
formulax=Brand.create("name" => "Formula X")
fresh=Brand.create("name" => "Fresh")
ghd=Brand.create("name" => "ghd")
giorgioarmani=Brand.create("name" => "Giorgio Armani")
givenchy=Brand.create("name" => "Givenchy")
glamglow=Brand.create("name" => "GLAMGLOW")
glo=Brand.create("name" => "GLO")
gucci=Brand.create("name" => "Gucci")
guerlain=Brand.create("name" => "Guerlain")
hairmax=Brand.create("name" => "HairMax")
hamptonsun=Brand.create("name" => "Hampton Sun")
hanaemori=Brand.create("name" => "Hanae Mori")
harajukulovers=Brand.create("name" => "Harajuku Lovers")
hellokitty=Brand.create("name" => "Hello Kitty")
hermes=Brand.create("name" => "HERMÈS")
hourglass=Brand.create("name" => "Hourglass")
hugoboss=Brand.create("name" => "Hugo Boss")
ilovenewyorkbybondno9=Brand.create("name" => "I LOVE NEW YORK by Bond No. 9")
illamasqua=Brand.create("name" => "Illamasqua")
isseymiyake=Brand.create("name" => "Issey Miyake")
jackblack=Brand.create("name" => "Jack Black")
jeanpaulgaultier=Brand.create("name" => "Jean Paul Gaultier")
jenniferaniston=Brand.create("name" => "Jennifer Aniston")
jimmychoo=Brand.create("name" => "JIMMY CHOO")
jinsoon=Brand.create("name" => "JINsoon")
johnvarvatos=Brand.create("name" => "John Varvatos")
josiemaran=Brand.create("name" => "Josie Maran")
juicycouture=Brand.create("name" => "Juicy Couture")
julep=Brand.create("name" => "Julep")
jurlique=Brand.create("name" => "Jurlique")
karuna=Brand.create("name" => "Karuna")
katvond=Brand.create("name" => "Kat Von D")
katesomerville=Brand.create("name" => "Kate Somerville")
kiehls=Brand.create("name" => "Kiehls")
kenzo=Brand.create("name" => "Kenzo")
keratinperfect=Brand.create("name" => "KeratinPerfect")
kohgendo=Brand.create("name" => "Koh Gen Do")
korres=Brand.create("name" => "Korres")
lartisanparfumeur=Brand.create("name" => "L'Artisan Parfumeur")
loccitane=Brand.create("name" => "L'Occitane")
labseriesformen=Brand.create("name" => "Lab Series For Men")
lacoste=Brand.create("name" => "Lacoste")
lancome=Brand.create("name" => "Lancôme")
lashfood=Brand.create("name" => "LASHFOOD")
lauramercier=Brand.create("name" => "Laura Mercier")
lavanila=Brand.create("name" => "LAVANILA")
leajourno=Brand.create("name" => "Lea Journo")
litcosmetics=Brand.create("name" => "Lit Cosmetics")
livingproof=Brand.create("name" => "Living Proof")
lorac=Brand.create("name" => "LORAC")
maisonmartinmargiela=Brand.create("name" => "MAISON MARTIN MARGIELA")
makeupforever=Brand.create("name" => "MAKE UP FOR EVER")
manukadoctor=Brand.create("name" => "Manuka Doctor")
marcjacobsbeauty=Brand.create("name" => "Marc Jacobs Beauty")
marcjacobsfragrance=Brand.create("name" => "Marc Jacobs Fragrance")
marchesa=Brand.create("name" => "MARCHESA")
marula=Brand.create("name" => "Marula")
masqueology=Brand.create("name" => "Masque*ology")
mdsolarsciences=Brand.create("name" => "MDSolarSciences")
mesmooth=Brand.create("name" => "me smooth")
michaelkors=Brand.create("name" => "Michael Kors")
montblanc=Brand.create("name" => "Montblanc")
murad=Brand.create("name" => "Murad")
mustela=Brand.create("name" => "Mustela")
nailsinc=Brand.create("name" => "nails inc.")
narcisorodriguez=Brand.create("name" => "Narciso Rodriguez")
nars=Brand.create("name" => "NARS")
nest=Brand.create("name" => "NEST")
thenewblack=Brand.create("name" => "The New Black")
nobleedinglips=Brand.create("name" => "No Bleeding Lips")
nubrilliance=Brand.create("name" => "Nu Brilliance")
nudeskincare=Brand.create("name" => "NUDE Skincare")
nuface=Brand.create("name" => "NuFACE")
obsessivecompulsivecosmetics=Brand.create("name" => "Obsessive Compulsive Cosmetics")
ojon=Brand.create("name" => "Ojon")
olehenriksen=Brand.create("name" => "Ole Henriksen")
omorovicza=Brand.create("name" => "Omorovicza")
onedirection=Brand.create("name" => "One Direction")
origins=Brand.create("name" => "Origins")
oscarblandi=Brand.create("name" => "Oscar Blandi")
ouidad=Brand.create("name" => "Ouidad")
pacorabanne=Brand.create("name" => "Paco Rabanne")
perfectformula=Brand.create("name" => "Perfect Formula")
perfekt=Brand.create("name" => "Perfekt")
perriconemd=Brand.create("name" => "Perricone MD")
peterthomasroth=Brand.create("name" => "Peter Thomas Roth")
philosophy=Brand.create("name" => "Philosophy")
phyto=Brand.create("name" => "Phyto")
pinchprovisions=Brand.create("name" => "Pinch Provisions")
pinksugar=Brand.create("name" => "Pink Sugar")
prada=Brand.create("name" => "Prada")
radicalskincare=Brand.create("name" => "Radical Skincare")
ralphlauren=Brand.create("name" => "Ralph Lauren")
ren=Brand.create("name" => "REN")
riiviva=Brand.create("name" => "Riiviva")
ritahazan=Brand.create("name" => "Rita Hazan")
rosebudperfumeco=Brand.create("name" => "Rosebud Perfume Co.")
sachajuan=Brand.create("name" => "Sachajuan")
sephorabyopi=Brand.create("name" => "SEPHORA by OPI")
sephoracollection=Brand.create("name" => "SEPHORA COLLECTION")
sephorafavorites=Brand.create("name" => "Sephora Favorites")
sephorapantoneuniverse=Brand.create("name" => "SEPHORA+PANTONE UNIVERSE")
shaveworks=Brand.create("name" => "Shaveworks")
shiseido=Brand.create("name" => "Shiseido")
silkn=Brand.create("name" => "Silk'n")
skii=Brand.create("name" => "SK-II")
smashbox=Brand.create("name" => "Smashbox")
soapglory=Brand.create("name" => "Soap & Glory")
sponge=Brand.create("name" => "Sponge")
sttropeztanningessentials=Brand.create("name" => "St. Tropez Tanning Essentials")
stellamccartney=Brand.create("name" => "Stella McCartney")
stila=Brand.create("name" => "Stila")
sultra=Brand.create("name" => "Sultra")
sundayriley=Brand.create("name" => "Sunday Riley")
supergoop=Brand.create("name" => "Supergoop!")
t3=Brand.create("name" => "T3")
tanda=Brand.create("name" => "Tanda")
tangleteezer=Brand.create("name" => "Tangle Teezer")
tantowel=Brand.create("name" => "TanTowel")
tarte=Brand.create("name" => "Tarte")
tataharper=Brand.create("name" => "Tata Harper")
tatcha=Brand.create("name" => "Tatcha")
tenoverten=Brand.create("name" => "tenoverten")
thebalm=Brand.create("name" => "TheBalm")
thierrymugler=Brand.create("name" => "Thierry Mugler")
toccabeauty=Brand.create("name" => "Tocca Beauty")
tokyomilkdark=Brand.create("name" => "TokyoMilk Dark")
tomford=Brand.create("name" => "TOM FORD")
toofaced=Brand.create("name" => "Too Faced")
toppik=Brand.create("name" => "Toppik")
toryburch=Brand.create("name" => "Tory Burch")
tria=Brand.create("name" => "Tria")
tweezerman=Brand.create("name" => "Tweezerman")
urbandecay=Brand.create("name" => "Urban Decay")
valuesinsideout=Brand.create("name" => "Values Inside Out")
versace=Brand.create("name" => "Versace")
versoskincare=Brand.create("name" => "VERSO SKINCARE")
viktorrolf=Brand.create("name" => "Viktor & Rolf")
vitaliberata=Brand.create("name" => "Vita Liberata")
wei=Brand.create("name" => "Wei")
wenbychazdean=Brand.create("name" => "WEN® by Chaz Dean")
whenbrand=Brand.create("name" => "When")
twentyone=Brand.create("name" => "21 Drops")

Category.delete_all
cleanser=Category.create("name" => "Cleanser")
moisturizer=Category.create("name" => "Moisturizer")
treatment=Category.create("name" => "Treatment")
sunscreen=Category.create("name" => "Sunscreen")
tanning=Category.create("name" => "Tanning")
other=Category.create("name" => "Other")

SkinType.delete_all
dry=SkinType.create("name" => "Dry")
oily=SkinType.create("name" => "Oily")
combo=SkinType.create("name" => "Combination")
normal=SkinType.create("name" => "Normal")

ProductType.delete_all
facewash_cleanser=ProductType.create("category_id" => cleanser.id, "name" => "Face Wash & Cleanser")
exfoliators=ProductType.create("category_id" => cleanser.id, "name" => "Exfoliators")
toners=ProductType.create("category_id" => cleanser.id, "name" => "Toners")
makeup_remover=ProductType.create("category_id" => cleanser.id, "name" => "Makeup Remover")
cleansing_brushes_tools=ProductType.create("category_id" => cleanser.id, "name" => "Cleansing Brushes & Tools")
moisturizer_product=ProductType.create("category_id" => moisturizer.id, "name" => "Moisturizer")
nightcream=ProductType.create("category_id" => moisturizer.id, "name" => "Night Cream")
bbcreamcccream=ProductType.create("category_id" => moisturizer.id, "name" => "BB Cream & CC Cream")
tintedmoisturizer=ProductType.create("category_id" => moisturizer.id, "name" => "Tinted Moisturizer")
faceoil=ProductType.create("category_id" => moisturizer.id, "name" => "Face Oil")
facemist=ProductType.create("category_id" => moisturizer.id, "name" => "Face Mist")
eyecream=ProductType.create("category_id" => moisturizer.id, "name" => "Eye Cream")
decolleteneckcream=ProductType.create("category_id" => moisturizer.id, "name" => "Decollete & Neck Cream")
lipbalmtreatments=ProductType.create("category_id" => moisturizer.id, "name" => "Lip Balm & Treatments")
faceserumtreatments=ProductType.create("category_id" => treatment.id, "name" => "Face Serum & Treatments")
blemishacnetreatments=ProductType.create("category_id" => treatment.id, "name" => "Blemish & Acne Treatments")
facemasks=ProductType.create("category_id" => treatment.id, "name" => "Face Masks")
facial_peels=ProductType.create("category_id" => treatment.id, "name" => "Facial Peels")
eye_treatments=ProductType.create("category_id" => treatment.id, "name" => "Eye Treatments")
facesunscreen=ProductType.create("category_id" => sunscreen.id, "name" => "Face")
facetanning=ProductType.create("category_id" => tanning.id, "name" => "Face")
cellulite_stretchmarks=ProductType.create("category_id" => other.id, "name" => "Cellulite & Stretch Marks")
hair_removal=ProductType.create("category_id" => other.id, "name" => "Hair Removal")
teeth_whitening=ProductType.create("category_id" => other.id, "name" => "Teeth Whitening")
mother_baby=ProductType.create("category_id" => other.id, "name" => "Mother & Baby")
supplements=ProductType.create("category_id" => other.id, "name" => "Supplements")
oilcontrol_blottingpaper=ProductType.create("category_id" => other.id, "name" => "Oil Control & Blotting Paper")

Product.delete_all
korresm=Product.create("brand_id" => korres.id, "product_type_id" => nightcream.id, "description" => "A weightless soufflé powered by super-charged proteins that melts into skin and works overnight for intense, immediate moisturization.", "price" => "45", "skintype_id" => combo.id, "review_count" => "318", "rating" => "4.5", "link" => "http://www.sephora.com/greek-yoghurt-advanced-nourishing-sleeping-facial-P379063?skuId=1522606", "image" => "http://www.sephora.com/productimages/sku/s1522606-main-hero.jpg")
glamglowm=Product.create("brand_id" => glamglow.id, "product_type_id" => nightcream.id, "description" => "A nondrying hydration mask to deliver instant, extreme hydration.", "price" => "69", "skintype_id" => combo.id, "review_count" => "228", "rating" => "4.3", "link" => "http://www.sephora.com/thirstymud-tm-hydrating-treatment-P384782?skuId=1582725", "image" => "http://www.sephora.com/productimages/sku/s1582725-main-hero.jpg")
originsm=Product.create("brand_id" => origins.id, "product_type_id" => nightcream.id, "description" => "A night cream so skin wakes up radiant and refreshed.", "price" => "39.5", "skintype_id" => combo.id, "review_count" => "323", "rating" => "4.4", "link" => "http://www.sephora.com/high-potency-night-a-mins-mineral-enriched-renewal-cream-P297520?skuId=1375724", "image" => "http://www.sephora.com/productimages/sku/s1375724-main-hero.jpg")
cliniquem=Product.create("brand_id" => clinique.id, "product_type_id" => moisturizer_product.id, "description" => "A luxurious moisturizer that promotes smooth, healthy-looking skin.", "price" => "26", "skintype_id" => combo.id, "review_count" => "355", "rating" => "3.7", "link" => "http://www.sephora.com/dramatically-different-moisturizing-lotion-P381030?skuId=1538354#BVRRWidgetID", "image" => "http://www.sephora.com/productimages/sku/s1538354-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => moisturizer_product.id, "description" => "A lightweight, oil-free hydrator for combination and oily skin.", "price" => "26", "skintype_id" => combo.id, "review_count" => "2043", "rating" => "4.5", "link" => "http://www.sephora.com/dramatically-different-moisturizing-gel-P122900?skuId=789727", "image" => "http://www.sephora.com/productimages/sku/s789727-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => moisturizer_product.id, "description" => "A refreshing cream-gel that instantly replenishes skin with 24 hours of soothing hydration.", "price" => "49.5", "skintype_id" => combo.id, "review_count" => "1831", "rating" => "4.5", "link" => "http://www.sephora.com/moisture-surge-extended-thirst-relief-P209117?skuId=1084805", "image" => "http://www.sephora.com/productimages/sku/s1084821-main-hero.jpg")
shiseidom=Product.create("brand_id" => shiseido.id, "product_type_id" => nightcream.id, "description" => "A multi-action nighttime revitalizer that counteracts signs of daytime damage.", "price" => "42.5", "skintype_id" => combo.id, "review_count" => "13", "rating" => "4.6", "link" => "http://www.sephora.com/the-skincare-night-moisture-recharge-enriched-P173638?skuId=986778", "image" => "http://www.sephora.com/productimages/sku/s986778-main-hero.jpg")
Product.create("brand_id" => josiemaran.id, "product_type_id" => faceoil.id, "description" => "A lightweight oil that can be used as a daily moisturizer or treatment for skin, hair, and nails.", "price" => "96", "skintype_id" => combo.id, "review_count" => "5143", "rating" => "4.5", "link" => "http://www.sephora.com/100-percent-pure-argan-oil-P218700?skuId=1121797", "image" => "http://www.sephora.com/productimages/sku/s1121797-main-hero.jpg")
freshm=Product.create("brand_id" => fresh.id, "product_type_id" => moisturizer_product.id, "description" => "A daily age-defying moisturizer formulated with Fresh’s proprietary Super 7 Complex, proven to prevent the signs of aging, provide 24 hours of significant moisture, and boost radiance.", "price" => "42", "skintype_id" => combo.id, "review_count" => "508", "rating" => "4.3", "link" => "http://www.sephora.com/lotus-youth-preserve-face-cream-with-super-7-complex-P377123?skuId=1488352", "image" => "http://www.sephora.com/productimages/sku/s1488352-main-hero.jpg")
Product.create("brand_id" => firstaidbeauty.id, "product_type_id" => moisturizer_product.id, "description" => "An over-the-counter, super-emollient cream with a spectacular whipped, non-greasy texture.", "price" => "28", "skintype_id" => combo.id, "review_count" => "2945", "rating" => "4.7", "link" => "http://www.sephora.com/ultra-repair-cream-P248407?skuId=1217744", "image" => "http://www.sephora.com/productimages/sku/s1217744-main-hero.jpg")
Product.create("brand_id" => olehenriksen.id, "product_type_id" => moisturizer_product.id, "description" => "A lightweight, silky moisturizer that nourishes skin as it gently exfoliates and fades dark spots.", "price" => "58", "skintype_id" => combo.id, "review_count" => "1030", "rating" => "4.4", "link" => "http://www.sephora.com/sheer-transformation-P42342?skuId=958611", "image" => "http://www.sephora.com/productimages/sku/s958611-main-hero.jpg")
Product.create("brand_id" => philosophy.id, "product_type_id" => moisturizer_product.id, "description" => "A cult-favorite moisturizer that gently hydrates, exfoliates, and protects the skin.", "price" => "67", "skintype_id" => combo.id, "review_count" => "6289", "rating" => "4", "link" => "http://www.sephora.com/hope-in-a-jar-P4633?skuId=351841", "image" => "http://www.sephora.com/productimages/sku/s1051887-main-hero.jpg")
Product.create("brand_id" => fresh.id, "product_type_id" => faceoil.id, "description" => "A soothing face oil packed with restorative omegas and seabuckthorn oil to preserve a youthful appearance.", "price" => "50", "skintype_id" => combo.id, "review_count" => "452", "rating" => "4.4", "link" => "http://www.sephora.com/seaberry-moisturizing-face-oil-P374948?skuId=1448745", "image" => "http://www.sephora.com/productimages/sku/s1448745-main-hero.jpg")
Product.create("brand_id" => jurlique.id, "product_type_id" => facemist.id, "description" => "A complexion balancing mist.", "price" => "35", "skintype_id" => combo.id, "review_count" => "148", "rating" => "4.4", "link" => "http://www.sephora.com/rosewater-balancing-mist-P224506?skuId=1430032", "image" => "http://www.sephora.com/productimages/sku/s1430032-main-hero.jpg")
Product.create("brand_id" => caudalie.id, "product_type_id" => facemist.id, "description" => "Part-toner, part-serum mist of essential oils and plant active ingredients.", "price" => "49", "skintype_id" => combo.id, "review_count" => "1706", "rating" => "4.4", "link" => "http://www.sephora.com/beauty-elixir-P6025?skuId=455774", "image" => "http://www.sephora.com/productimages/sku/s1231182-main-hero.jpg")
Product.create("brand_id" => shiseido.id, "product_type_id" => eyecream.id, "description" => "An ultrarich, age-defying cream that visibly improves the appearance of all types of eye area wrinkles.", "price" => "55", "skintype_id" => combo.id, "review_count" => "976", "rating" => "4.4", "link" => "http://www.sephora.com/benefiance-wrinkleresist24-intensive-eye-contour-cream-P173620?skuId=1408202", "image" => "http://www.sephora.com/productimages/sku/s1408202-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => eye_treatments.id, "description" => "A moisturizing eye treatment that helps minimize the look of dark circles, shadows, and puffiness.", "price" => "50", "skintype_id" => combo.id, "review_count" => "974", "rating" => "4.2", "link" => "http://www.sephora.com/all-about-eyes-rich-P174502?skuId=971473", "image" => "http://www.sephora.com/productimages/sku/s971473-main-hero.jpg")
Product.create("brand_id" => philosophy.id, "product_type_id" => moisturizer_product.id, "description" => "A rejuvenating, age-fighting hydrator that softens, firms, and brightens the complexion.", "price" => "96", "skintype_id" => combo.id, "review_count" => "1029", "rating" => "4.4", "link" => "http://www.sephora.com/miracle-worker-miraculous-anti-aging-moisturizer-P254209?skuId=1229442", "image" => "http://www.sephora.com/productimages/sku/s1229442-main-hero.jpg")
Product.create("brand_id" => josiemaran.id, "product_type_id" => faceoil.id, "description" => "An ultralightweight, quick-absorbing version of Josie’s cult-favorite 100% Pure Argan Oil.", "price" => "48", "skintype_id" => combo.id, "review_count" => "534", "rating" => "4.4", "link" => "http://www.sephora.com/100-pure-argan-oil-light-P380805?skuId=1548270", "image" => "http://www.sephora.com/productimages/sku/s1548288-main-hero.jpg")
Product.create("brand_id" => jackblack.id, "product_type_id" => lipbalmtreatments.id, "description" => "A hydrating lip balm to soothe lips while it protects from sun and wind.", "price" => "7.5", "skintype_id" => combo.id, "review_count" => "1838", "rating" => "4.7", "link" => "http://www.sephora.com/intense-therapy-lip-balm-spf-25-P12573?skuId=564344", "image" => "http://www.sephora.com/productimages/sku/s564344-main-hero.jpg")
Product.create("brand_id" => kiehls.id, "product_type_id" => moisturizer_product.id, "description" => "A 24-hour daily face moisturizer.", "price" => "46.5", "skintype_id" => combo.id, "review_count" => "236", "rating" => "4.8", "link" => "http://www.kiehls.com/Ultra-Facial-Cream/622,default,pd.html?start=1&cgid=face-moisturizers", "image" => "http://www.sephora.com/productimages/sku/s1408202-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => faceoil.id, "name" => "Take The Day Off Cleansing Oil", "description" => "A cleansing oil to immediately dissolve tenacious face makeup, oil, and impurities.", "price" => "27", "skintype_id" => combo.id, "review_count" => "27", "rating" => "4.4", "link" => "http://www.sephora.com/take-the-day-off-cleansing-oil-P384821?skuId=1583426", "image" => "http://www.sephora.com/productimages/sku/s1583426-main-hero.jpg")
Product.create("brand_id" => philosophy.id, "product_type_id" => facewash_cleanser.id, "name" => "Purity Made Simple", "description" => "A highly effective one-step facial cleanser.", "price" => "23", "skintype_id" => combo.id, "review_count" => "8242", "rating" => "4.6", "link" => "http://www.sephora.com/purity-made-simple-P7109?skuId=407304", "image" => "http://www.sephora.com/productimages/sku/s407304-main-hero.jpg")
Product.create("brand_id" => fresh.id, "product_type_id" => facewash_cleanser.id, "name" => "Soy Face Cleanser", "description" => "A multitasking gel that gently removes impurities and makeup.", "price" => "38", "skintype_id" => combo.id, "review_count" => "2646", "rating" => "4.5", "link" => "http://www.sephora.com/soy-face-cleanser-P7880?skuId=487694", "image" => "http://www.sephora.com/productimages/sku/s487694-main-hero.jpg")
Product.create("brand_id" => evelom.id, "product_type_id" => facewash_cleanser.id, "name" => "Cleanser", "description" => "An iconic, multiaward-winning cleanser that cleanses, decongests, tones, exfoliates, and removes even the most stubborn waterproof makeup.", "price" => "80", "skintype_id" => combo.id, "review_count" => "66", "rating" => "4.3", "link" => "http://www.sephora.com/cleanser-P381436?skuId=1560200", "image" => "http://www.sephora.com/productimages/sku/s1560200-main-hero.jpg")
Product.create("brand_id" => boscia.id, "product_type_id" => facewash_cleanser.id, "name" => "Detoxifying Black Cleanser", "description" => "A warming gel cleanser that deeply cleans and detoxifies the complexion.", "price" => "28", "skintype_id" => combo.id, "review_count" => "724", "rating" => "4.3", "link" => "http://www.sephora.com/detoxifying-black-cleanser-P302940?skuId=1393057", "image" => "http://www.sephora.com/productimages/sku/s1393057-main-hero.jpg")
Product.create("brand_id" => philosophy.id, "product_type_id" => facewash_cleanser.id, "name" => "The Microdelivery Exfoilating Wash", "description" => "A mild, exfoliating facial cleanser", "price" => "28", "skintype_id" => combo.id, "review_count" => "2688", "rating" => "4.6", "link" => "http://www.sephora.com/the-microdelivery-exfoliating-wash-P184109?skuId=976399", "image" => "http://www.sephora.com/productimages/sku/s976399-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => facewash_cleanser.id, "name" => "Liquid Facial Soap", "description" => "A non-drying liquid soap that cleanses gently and thoroughly.", "price" => "16.5", "skintype_id" => combo.id, "review_count" => "1448", "rating" => "4.4", "link" => "http://www.sephora.com/liquid-facial-soap-P139000?skuId=899070", "image" => "http://www.sephora.com/productimages/sku/s899070-main-hero.jpg")
Product.create("brand_id" => olehenriksen.id, "product_type_id" => facewash_cleanser.id, "name" => "African Red Tea Foaming Cleanser", "description" => "A uniquely rich and creamy foaming cleanser melts away dirt, oil, and makeup without stripping the skin of essential moisture", "price" => "30", "skintype_id" => combo.id, "review_count" => "873", "rating" => "4.5", "link" => "http://www.sephora.com/african-red-tea-foaming-cleanser-P211343?skuId=1087576", "image" => "http://www.sephora.com/productimages/sku/s1087576-main-hero.jpg")
Product.create("brand_id" => glamglow.id, "product_type_id" => facemasks.id, "name" => "YOUTHMUD™ TINGLEXFOLIATE TREATMENT", "description" => "A 10-minute professional-quality mud mask for men and women.", "price" => "69", "skintype_id" => combo.id, "review_count" => "900", "rating" => "4.1", "link" => "http://www.sephora.com/productimages/sku/s1463801-main-hero.jpg", "image" => "http://www.sephora.com/productimages/sku/s1463801-main-hero.jpg")
Product.create("brand_id" => fresh.id, "product_type_id" => exfoliators.id, "name" => "Sugar Face Polish", "description" => "A nourishing, exfoliating mask that refines and brightens the skin, instantly revealing a radiant complexion.", "price" => "58", "skintype_id" => combo.id, "review_count" => "430", "rating" => "4.6", "link" => "http://www.sephora.com/sugar-face-polish-P12295?skuId=562082", "image" => "http://www.sephora.com/productimages/sku/s562082-main-hero.jpg")
Product.create("brand_id" => katesomerville.id, "product_type_id" => exfoliators.id, "name" => "ExfoliKate® Intensive Exfoliating Treatment", "description" => "A dual-action exfoliation method that seemingly smooths away years in as little as two minutes. .", "price" => "85", "skintype_id" => combo.id, "review_count" => "1444", "rating" => "4.4", "link" => "http://www.sephora.com/exfolikate-intensive-exfoliating-treatment-P232915?skuId=1201748", "image" => "http://www.sephora.com/productimages/sku/s1201748-main-hero.jpg")
Product.create("brand_id" => lauramercier.id, "product_type_id" => exfoliators.id, "name" => "Flawless Skin Face Polish", "description" => "A creamy cleansing face scrub.", "price" => "32", "skintype_id" => combo.id, "review_count" => "480", "rating" => "4.7", "link" => "http://www.sephora.com/flawless-skin-face-polish-P280925?skuId=1314723", "image" => "http://www.sephora.com/productimages/sku/s1314723-main-hero.jpg")
Product.create("brand_id" => skii.id, "product_type_id" => faceserumtreatments.id, "name" => "Facial Treatment Essence", "description" => "A refreshing essence that moisturizes the skin and supports skin cell renewal.", "price" => "100", "skintype_id" => combo.id, "review_count" => "171", "rating" => "4.2", "link" => "http://www.sephora.com/facial-treatment-essence-P375849?skuId=1448612", "image" => "http://www.sephora.com/productimages/sku/s1448612-main-hero.jpg")
Product.create("brand_id" => fresh.id, "product_type_id" => facemist.id, "name" => "Rose floral toner", "description" => "An alcohol-free blend of hydrating and toning floral waters, collected and extracted in Grasse, France.", "price" => "38", "skintype_id" => combo.id, "review_count" => "222", "rating" => "4.4", "link" => "http://www.sephora.com/rose-marigold-floral-water-P39970?skuId=661157", "image" => "http://www.sephora.com/productimages/sku/s661157-main-hero.jpg")
Product.create("brand_id" => caudalie.id, "product_type_id" => facemist.id, "name" => "Beauty Elixir", "description" => "Part-toner, part-serum mist of essential oils and plant active ingredients.", "price" => "18", "skintype_id" => combo.id, "review_count" => "1706", "rating" => "4.4", "link" => "http://www.sephora.com/beauty-elixir-P6025?skuId=455774", "image" => "http://www.sephora.com/productimages/sku/s455774-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => toners.id, "name" => "Clarifying Lotion 2", "description" => "A gentle, oil-free exfoliating lotion for dry or combination skin.", "price" => "13", "skintype_id" => combo.id, "review_count" => "901", "rating" => "4.4", "link" => "http://www.sephora.com/clarifying-lotion-2-P122882?skuId=1295708", "image" => "http://www.sephora.com/productimages/sku/s1295708-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => exfoliators.id, "name" => "Exfoliating Scrub", "description" => "A water-based scrub for oily skin.", "price" => "19.5", "skintype_id" => oily.id, "review_count" => "726", "rating" => "4.8", "link" => "http://www.sephora.com/exfoliating-scrub-P122718?skuId=579490", "image" => "http://www.sephora.com/productimages/sku/s579490-main-hero.jpg")
Product.create("brand_id" => drbrandtskincare.id, "product_type_id" => exfoliators.id, "name" => "microdermabrasion skin exfoliant", "description" => "A powerful at-home alternative to in-office skin exfoliation procedures.", "price" => "78", "skintype_id" => combo.id, "review_count" => "659", "rating" => "4.7", "link" => "http://www.sephora.com/microdermabrasion-skin-exfoliant-P45503?skuId=1161520", "image" => "http://www.sephora.com/productimages/sku/s1161520-main-hero.jpg")
Product.create("brand_id" => origins.id, "product_type_id" => exfoliators.id, "name" => "Modern Friction™ Nature's Gentle Dermabrasion", "description" => "An age-smoothing exfoliation product for perfectly polished, smooth, and luminous skin.", "price" => "39.5", "skintype_id" => combo.id, "review_count" => "201", "rating" => "4.5", "link" => "http://www.sephora.com/modern-friction-nature-s-gentle-dermabrasion-P297513?skuId=1375658", "image" => "http://www.sephora.com/productimages/sku/s1375658-main-hero.jpg")
Product.create("brand_id" => olehenriksen.id, "product_type_id" => faceserumtreatments.id, "name" => "Truth Serum® Vitamin C Collagen Booster", "description" => "An antioxidant-rich brightening and nourishing serum enriched with vitamin C.", "price" => "48", "skintype_id" => combo.id, "review_count" => "1961", "rating" => "4.4", "link" => "http://www.sephora.com/truth-serum-vitamin-c-collagen-booster-P42343?skuId=965681", "image" => "http://www.sephora.com/productimages/sku/s965681-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => faceserumtreatments.id, "name" => "Even Better Clinical Dark Spot Corrector", "description" => "A serum clinically proven to visibly reduce dark spots, age spots, and traces of past acne.", "price" => "49.5", "skintype_id" => combo.id, "review_count" => "1940", "rating" => "3.7", "link" => "http://www.sephora.com/even-better-clinical-dark-spot-corrector-P257535?skuId=1246644", "image" => "http://www.sephora.com/productimages/sku/s1246644-main-hero.jpg")
Product.create("brand_id" => esteelauder.id, "product_type_id" => faceserumtreatments.id, "name" => "Advanced Night Repair Synchronized Recovery Complex II", "description" => "A high-performance antiaging serum to fight all key signs of visible aging.", "price" => "92", "skintype_id" => combo.id, "review_count" => "27", "rating" => "4.8", "link" => "http://www.sephora.com/advanced-night-repair-synchronized-recovery-complex-ii-P379994?skuId=1551753", "image" => "http://www.sephora.com/productimages/sku/s1551753-main-hero.jpg")
Product.create("brand_id" => glamglow.id, "product_type_id" => facemasks.id, "name" => "SUPERMUD™ CLEARING TREATMENT", "description" => "A scientifically advanced SUPER-MUD™ clearing treatment to target, prevent, and heal problem skin.", "price" => "69", "skintype_id" => combo.id, "review_count" => "1132", "rating" => "4.3", "link" => "http://www.sephora.com/super-mud-clearing-treatment-P376409?skuId=1473735", "image" => "http://www.sephora.com/productimages/sku/s1473735-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => blemishacnetreatments.id, "name" => "Acne Solutions Clinical Clearing Gel", "description" => "An allergy tested, fragrance-free daily treatment gel with results as good as a leading topical prescription in clearing acne.", "price" => "25", "skintype_id" => combo.id, "review_count" => "133", "rating" => "4.4", "link" => "http://www.sephora.com/acne-solutions-clinical-clearing-gel-P385432?skuId=1592831", "image" => "http://www.sephora.com/productimages/sku/s1592831-main-hero.jpg")
Product.create("brand_id" => clearogen.id, "product_type_id" => blemishacnetreatments.id, "name" => "Three Step Acne Treatment Set", "description" => "A clinically proven three-piece acne regimen to clear existing acne and prevent future breakouts.", "price" => "39.5", "skintype_id" => combo.id, "review_count" => "7", "rating" => "4.3", "link" => "http://www.sephora.com/three-step-acne-treatment-set-P385453?skuId=1608710", "image" => "http://www.sephora.com/productimages/sku/s1608710-main-hero.jpg")
Product.create("brand_id" => peterthomasroth.id, "product_type_id" => facemasks.id, "name" => "Therapeutic Sulfur Masque Acne Treatment Masque", "description" => "A skin-clearing masque that banishes blemishes and unclogs pores for a flawless complexion.", "price" => "40", "skintype_id" => oily.id, "review_count" => "387", "rating" => "4.5", "link" => "http://www.sephora.com/therapeutic-sulfur-masque-acne-treatment-masque-P3617?skuId=1446178", "image" => "http://www.sephora.com/productimages/sku/s1446178-main-hero.jpg")
Product.create("brand_id" => dermadoctor.id, "product_type_id" => faceserumtreatments.id, "name" => "Calm Cool & Corrected", "description" => "Calm Cool and Corrected aggressively (yet gently) and effectively targets matters that plagues rosacea-riddled skin (like blemishes, oiliness, redness, dryness, or sensitivity), as it helps diminish the visible signs of aging. This radical, calming treatment rescues and renews even the most irritated skin.", "price" => "85", "skintype_id" => combo.id, "review_count" => "224", "rating" => "4.2", "link" => "http://www.sephora.com/calm-cool-corrected-P73517?skuId=784421", "image" => "http://www.sephora.com/productimages/sku/s784421-main-hero.jpg")
Product.create("brand_id" => philosophy.id, "product_type_id" => blemishacnetreatments.id, "name" => "Clear Days Ahead™ Overnight Repair Salicylic Acid Acne Treatment Pads", "description" => "An easy-to-use, one-step acne treatment pad that reduces acne breakouts and promotes clearer skin.", "price" => "40", "skintype_id" => combo.id, "review_count" => "58", "rating" => "4.6", "link" => "http://www.sephora.com/clear-days-ahead-overnight-repair-salicylic-acid-acne-treatment-pads-P312003?skuId=1417211", "image" => "http://www.sephora.com/productimages/sku/s1417211-main-hero.jpg")
Product.create("brand_id" => katesomerville.id, "product_type_id" => faceserumtreatments.id, "name" => "EradiKate Acne Treatment", "description" => "An effective blemish-banishing therapy.", "price" => "22", "skintype_id" => oily.id, "review_count" => "1228", "rating" => "4.3", "link" => "http://www.sephora.com/eradikate-acne-treatment-P232903?skuId=1167147", "image" => "http://www.sephora.com/productimages/sku/s1167147-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => eye_treatments.id, "name" => "All About Eyes™ Rich", "description" => "A moisturizing eye treatment that helps minimize the look of dark circles, shadows, and puffiness.", "price" => "30", "skintype_id" => combo.id, "review_count" => "973", "rating" => "4.2", "link" => "http://www.sephora.com/all-about-eyes-rich-P174502?skuId=971473", "image" => "http://www.sephora.com/productimages/sku/s971473-main-hero.jpg")
Product.create("brand_id" => algenist.id, "product_type_id" => eye_treatments.id, "name" => "Firming & Lifting Eye Gel", "description" => "A lightweight and refreshing gel that rebuilds skin density to firm and lift the delicate skin around the eyes.", "price" => "68", "skintype_id" => combo.id, "review_count" => "94", "rating" => "4.3", "link" => "http://www.sephora.com/firming-lifting-eye-gel-P304007?skuId=1394279", "image" => "http://www.sephora.com/productimages/sku/s1394279-main-hero.jpg")
Product.create("brand_id" => drdennisgrossskincare.id, "product_type_id" => facial_peels.id, "name" => "Alpha Beta® Peel Extra Strength Formula", "description" => "An extra-strength version of this bestselling antiaging treatment.", "price" => "86", "skintype_id" => combo.id, "review_count" => "632", "rating" => "4.5", "link" => "http://www.sephora.com/alpha-beta-peel-extra-strength-formula-P269122?skuId=1499482", "image" => "http://www.sephora.com/productimages/sku/s1499482-main-hero.jpg")
Product.create("brand_id" => peterthomasroth.id, "product_type_id" => facial_peels.id, "name" => "40% Triple Acid Peel", "description" => "A professional-grade peel that delivers an expert, advanced treatment to your home—with less risk of irritation and less recovery time.", "price" => "88", "skintype_id" => combo.id, "review_count" => "120", "rating" => "4.1", "link" => "http://www.sephora.com/40-triple-acid-peel-P384556?skuId=1584929", "image" => "http://www.sephora.com/40-triple-acid-peel-P384556?skuId=1584929")
Product.create("brand_id" => fresh.id, "product_type_id" => faceserumtreatments.id, "name" => "Peony Spot-Correcting Brightening Essence", "description" => "A highly effective formula to brighten skintone, clarify, lighten, and visibly reduce the appearance of age spots and imperfections.", "price" => "65", "skintype_id" => combo.id, "review_count" => "5", "rating" => "5", "link" => "http://www.sephora.com/umbrian-clay-face-treatment-P54104?skuId=720946", "image" => "http://www.sephora.com/productimages/sku/s720946-main-hero.jpg")
Product.create("brand_id" => origins.id, "product_type_id" => blemishacnetreatments.id, "name" => "Super Spot Remover™ Acne Treatment Gel", "description" => "A blemish-busting acne spot treatment with salicylic acid.", "price" => "15", "skintype_id" => combo.id, "review_count" => "296", "rating" => "4.1", "link" => "http://www.sephora.com/super-spot-remover-acne-treatment-gel-P297517?skuId=1375690", "image" => "http://www.sephora.com/productimages/sku/s1375690-main-hero.jpg")
Product.create("brand_id" => fresh.id, "product_type_id" => facemasks.id, "name" => "Rose face mask", "description" => "A hydrating and toning mask with a cooling gel formula infused with pure rosewater and real rose petals.", "price" => "58", "skintype_id" => combo.id, "review_count" => "463", "rating" => "4.2", "link" => "http://www.sephora.com/rose-face-mask-P12336?skuId=562090", "image" => "http://www.sephora.com/productimages/sku/s562090-main-hero.jpg")
Product.create("brand_id" => murad.id, "product_type_id" => blemishacnetreatments.id, "name" => "Acne Clearing Solution", "description" => "A treatment that clears breakouts and manages acne-causing symptoms to help achieve healthy, blemish-free skin.", "price" => "39", "skintype_id" => combo.id, "review_count" => "27", "rating" => "3.6", "link" => "http://www.sephora.com/acne-clearing-solution-P385325?skuId=1602846", "image" => "http://www.sephora.com/productimages/sku/s1602846-main-hero.jpg")
Product.create("brand_id" => philosophy.id, "product_type_id" => facial_peels.id, "name" => "Resurface - The Microdelivery Dual-Phase Peel", "description" => "A two-step, exfoliating, skin makeover.", "price" => "70", "skintype_id" => combo.id, "review_count" => "1653", "rating" => "4.7", "link" => "http://www.sephora.com/resurface-the-microdelivery-dual-phase-peel-P72504?skuId=779983", "image" => "http://www.sephora.com/productimages/sku/s779983-main-hero.jpg")
Product.create("brand_id" => shiseido.id, "product_type_id" => facesunscreen.id, "name" => "Ultimate Sun Protection Lotion+ Broad Spectrum SPF 50+ For Face/Body", "description" => "A highly nourishing sunscreen lotion for the face and body.", "price" => "39", "skintype_id" => combo.id, "review_count" => "655", "rating" => "4.5", "link" => "http://www.sephora.com/ultimate-sun-protection-lotion-broad-spectrum-spf-50-for-face-body-P173670?skuId=1451970", "image" => "http://www.sephora.com/productimages/sku/s1451970-main-hero.jpg")
Product.create("brand_id" => josiemaran.id, "product_type_id" => facesunscreen.id, "name" => "Argan Daily Moisturizer SPF 47", "description" => "A new and improved hydrating, fast-absorbing, non-greasy, Argan Oil-infused daily moisturizer featuring all natural sunscreens, green tea, and innovative SunBoost ATB™.", "price" => "32", "skintype_id" => combo.id, "review_count" => "133", "rating" => "3.1", "link" => "http://www.sephora.com/argan-daily-moisturizer-spf-47-P385679?skuId=1585256", "image" => "http://www.sephora.com/productimages/sku/s1585256-main-hero.jpg")
Product.create("brand_id" => shiseido.id, "product_type_id" => facesunscreen.id, "name" => "Urban Environment Oil-Free UV Protector Broad Spectrum SPF 42 For Face", "description" => "An oil-free daily formulation that protects against three major causes of skin cell damage: UV rays, oxidation, and overproduction of sebum.", "price" => "30", "skintype_id" => oily.id, "review_count" => "248", "rating" => "4.5", "link" => "http://www.sephora.com/urban-environment-oil-free-uv-protector-broad-spectrum-spf-42-for-face-P307405?skuId=1452002", "image" => "http://www.sephora.com/productimages/sku/s1452002-main-hero.jpg")
Product.create("brand_id" => murad.id, "product_type_id" => facesunscreen.id, "name" => "Oil-Control Mattifier SPF 15 PA++", "description" => "A shine-reducing moisturizer that controls oil for up to eight hours, decreases breakouts, and protects skin.", "price" => "39.5", "skintype_id" => oily.id, "review_count" => "1313", "rating" => "4.1", "link" => "http://www.sephora.com/oil-control-mattifier-spf-15-pa-P227801?skuId=1133727", "image" => "http://www.sephora.com/productimages/sku/s1133727-main-hero.jpg")
Product.create("brand_id" => olehenriksen.id, "product_type_id" => facesunscreen.id, "name" => "Truth Revealed™ Vitamin C Super Crème SPF 15", "description" => "A luxurious day crème with anti-aging benefits.", "price" => "55", "skintype_id" => combo.id, "review_count" => "276", "rating" => "4.2", "link" => "http://www.sephora.com/truth-revealed-vitamin-c-super-creme-spf-15-P268015?skuId=1280007", "image" => "http://www.sephora.com/productimages/sku/s1280007-main-hero.jpg")
Product.create("brand_id" => shiseido.id, "product_type_id" => facesunscreen.id, "name" => "Ultimate Sun Protection Cream+ Broad Spectrum SPF 50+ For Face", "description" => "A powerful and highly nourishing sunscreen for the face.", "price" => "35", "skintype_id" => combo.id, "review_count" => "643", "rating" => "4.5", "link" => "http://www.sephora.com/ultimate-sun-protection-cream-broad-spectrum-spf-50-for-face-P173669?skuId=1451988", "image" => "http://www.sephora.com/productimages/sku/s1451988-main-hero.jpg")
Product.create("brand_id" => murad.id, "product_type_id" => facesunscreen.id, "name" => "Essential-C Day Moisture Broad Spectrum SPF 30 PA+++", "description" => "A powerful antioxidant-rich moisturizer that shields and revitalizes environmentally stressed skin.", "price" => "60", "skintype_id" => combo.id, "review_count" => "244", "rating" => "4.1", "link" => "http://www.sephora.com/essential-c-day-moisture-spf-30-broad-spectrum-spf-30-pa-P9940?skuId=1207174", "image" => "http://www.sephora.com/productimages/sku/s1207174-main-hero.jpg")
Product.create("brand_id" => algenist.id, "product_type_id" => facesunscreen.id, "name" => "Regenerative Anti-Aging Moisturizer SPF 20", "description" => "A moisturizer with SPF 20 sunscreen protection and the exclusive antiaging ingredient alguronic acid.", "price" => "90", "skintype_id" => combo.id, "review_count" => "80", "rating" => "4.5", "link" => "http://www.sephora.com/regenerative-anti-aging-moisturizer-spf-20-P282937?skuId=1449628", "image" => "http://www.sephora.com/productimages/sku/s1449628-main-hero.jpg")
Product.create("brand_id" => shiseido.id, "product_type_id" => facesunscreen.id, "name" => "Ultimate Sun Protection Spray Broad Spectrum SPF 50+ For Face/Body", "description" => "A convenient spray sunscreen that allows quick, easy application over large areas of skin, especially hard-to-reach areas.", "price" => "36", "skintype_id" => combo.id, "review_count" => "6", "rating" => "4.1", "link" => "http://www.sephora.com/ultimate-sun-protection-spray-broad-spectrum-spf-50-for-face-body-P385262?skuId=1594175", "image" => "http://www.sephora.com/productimages/sku/s1594175-main-hero.jpg")
Product.create("brand_id" => philosophy.id, "product_type_id" => facesunscreen.id, "name" => "Hope Oil-Free SPF", "description" => "An ultra-light daily moisturizer for normal to oily skin with SPF 30.", "price" => "42", "skintype_id" => combo.id, "review_count" => "379", "rating" => "4", "link" => "http://www.sephora.com/hope-oil-free-spf-P261132?skuId=1244870", "image" => "http://www.sephora.com/productimages/sku/s1244870-main-hero.jpg")
Product.create("brand_id" => peterthomasroth.id, "product_type_id" => facesunscreen.id, "name" => "Oily Problem Skin Instant Mineral Powder SPF 30", "description" => "A blemish-fighting, transparent, oil-free SPF 30 mineral powder in a convenient brush applicator.", "price" => "30", "skintype_id" => combo.id, "review_count" => "492", "rating" => "4", "link" => "http://www.sephora.com/oily-problem-skin-instant-mineral-powder-spf-30-P235909?skuId=1165844", "image" => "http://www.sephora.com/productimages/sku/s1165844-main-hero.jpg")
Product.create("brand_id" => clarins.id, "product_type_id" => facesunscreen.id, "name" => "UV Plus HP Broad Spectrum SPF 40 Sunscreen Multi-Protection", "description" => "A day cream that protects the skin from the sun, environmental pollution, and free radicals.", "price" => "41", "skintype_id" => combo.id, "review_count" => "251", "rating" => "4.5", "link" => "http://www.sephora.com/uv-plus-hp-day-screen-high-protection-spf-40-P282024?skuId=1312958", "image" => "http://www.sephora.com/productimages/sku/s1312958-main-hero.jpg")
Product.create("brand_id" => origins.id, "product_type_id" => facesunscreen.id, "name" => "A Perfect World™ SPF 25 Age-Defense Moisturizer with White Tea", "description" => "A moisturizer that helps delay the appearance of premature aging.", "price" => "41", "skintype_id" => combo.id, "review_count" => "165", "rating" => "4", "link" => "http://www.sephora.com/a-perfect-world-spf-25-age-defense-moisturizer-with-white-tea-P297515?skuId=1375674", "image" => "http://www.sephora.com/productimages/sku/s1375674-main-hero.jpg")
Product.create("brand_id" => shiseido.id, "product_type_id" => facesunscreen.id, "name" => "Benefiance WrinkleResist24 Day Cream SPF 15 PA++", "description" => "An age-defying daytime moisturizer that helps protect skin from damage caused by external aging factors such as UV rays.", "price" => "53", "skintype_id" => combo.id, "review_count" => "57", "rating" => "4.5", "link" => "http://www.sephora.com/benefiance-wrinkleresist24-day-cream-spf-15-pa-P282018?skuId=1316280", "image" => "http://www.sephora.com/productimages/sku/s1316280-main-hero.jpg")
Product.create("brand_id" => peterthomasroth.id, "product_type_id" => facesunscreen.id, "name" => "Instant Mineral Powder SPF 45", "description" => "A transparent SPF 45 mineral powder in a convenient brush applicator.", "price" => "30", "skintype_id" => combo.id, "review_count" => "755", "rating" => "4", "link" => "http://www.sephora.com/instant-mineral-powder-spf-45-P235908?skuId=1165737", "image" => "http://www.sephora.com/productimages/sku/s1165737-main-hero.jpg")
Product.create("brand_id" => perriconemd.id, "product_type_id" => facesunscreen.id, "name" => "Photo Plasma", "description" => "A unique oil-free broad spectrum SPF 30 moisturizer that delivers powerful antiaging benefits while protecting against damaging sun rays.", "price" => "69", "skintype_id" => combo.id, "review_count" => "164", "rating" => "4.1", "link" => "http://www.sephora.com/photo-plasma-P379495?skuId=1521368", "image" => "http://www.sephora.com/productimages/sku/s1521368-main-hero.jpg")
Product.create("brand_id" => origins.id, "product_type_id" => facesunscreen.id, "name" => "VitaZing™ SPF 15 Energy-Boosting Moisturizer with Mangosteen", "description" => "A multitasking moisturizer that hydrates, energizes and protects.", "price" => "35", "skintype_id" => combo.id, "review_count" => "317", "rating" => "4.2", "link" => "http://www.sephora.com/vitazing-spf-15-energy-boosting-moisturizer-with-mangosteen-P297521?skuId=1375732", "image" => "http://www.sephora.com/productimages/sku/s1375732-main-hero.jpg")
Product.create("brand_id" => supergoop.id, "product_type_id" => facesunscreen.id, "name" => "SPF 30+ City Sunscreen Serum With Uniprotect PT-3", "description" => "A multitasking broad spectrum SPF 30+ daily repair serum for skin exposed to the sun and environmental stresses, both in the past and the present.", "price" => "42", "skintype_id" => combo.id, "review_count" => "37", "rating" => "4.5", "link" => "http://www.sephora.com/spf-30-city-sunscreen-serum-with-uniprotect-pt-3-P282915?skuId=1328707", "image" => "http://www.sephora.com/productimages/sku/s1328707-main-hero.jpg")
Product.create("brand_id" => algenist.id, "product_type_id" => facesunscreen.id, "name" => "Ultra Lightweight UV Defense Fluid SPF 50", "description" => "An ultra-sheer, weightless fluid for everyday protection against broad-spectrum UVA/UVB damage.", "price" => "28", "skintype_id" => combo.id, "review_count" => "65", "rating" => "4.3", "link" => "http://www.sephora.com/ultra-lightweight-uv-defense-fluid-spf-50-P311143?skuId=1420223", "image" => "http://www.sephora.com/productimages/sku/s1420223-main-hero.jpg")
Product.create("brand_id" => philosophy.id, "product_type_id" => facesunscreen.id, "name" => "Hope In A Jar SPF 25", "description" => "A high-performance moisturizer with broad-spectrum sun protection.", "price" => "42", "skintype_id" => combo.id, "review_count" => "1500", "rating" => "3.9", "link" => "http://www.sephora.com/hope-in-a-jar-spf-25-P212415?skuId=1276617", "image" => "http://www.sephora.com/productimages/sku/s1276617-main-hero.jpg")
Product.create("brand_id" => olehenriksen.id, "product_type_id" => facesunscreen.id, "name" => "Protect The Truth™ Vitamin C SPF 50+ Sunscreen", "description" => "A lightweight antiaging barrier that provides protection from environmental factors and UVA and UVB rays.", "price" => "35", "skintype_id" => combo.id, "review_count" => "109", "rating" => "4", "link" => "http://www.sephora.com/protect-the-truth-vitamin-c-spf-50-sunscreen-P288109?skuId=1342658", "image" => "http://www.sephora.com/productimages/sku/s1342658-main-hero.jpg")
Product.create("brand_id" => peterthomasroth.id, "product_type_id" => facesunscreen.id, "name" => "Anti-Aging Defense Sunscreen Stick SPF 50", "description" => "A non-sticky cream with SPF 50 protection that dries weightless and undetectable to the touch.", "price" => "26", "skintype_id" => combo.id, "review_count" => "3", "rating" => "4", "link" => "http://www.sephora.com/anti-aging-defense-sunscreen-stick-spf-50-P386379?skuId=1609304", "image" => "http://www.sephora.com/productimages/sku/s1609304-main-hero.jpg")
Product.create("brand_id" => murad.id, "product_type_id" => facesunscreen.id, "name" => "Sheer Lustre Day Moisture Broad Spectrum SPF 15 PA+++", "description" => "A renewing moisturizer for hormonally aging skin that instantly hydrates and renews skin’s lustre.", "price" => "70", "skintype_id" => combo.id, "review_count" => "92", "rating" => "4", "link" => "http://www.sephora.com/sheer-lustre-day-moisture-broad-spectrum-spf-15-pa-P38216?skuId=646984", "image" => "http://www.sephora.com/productimages/sku/s646984-main-hero.jpg")
Product.create("brand_id" => mdsolarsciences.id, "product_type_id" => facesunscreen.id, "name" => "Mineral Crème Broad Spectrum SPF 50 UVA-UVB Sunscreen", "description" => "A naturally derived, mineral-based SPF 50 broad spectrum sunscreen specifically formulated for acne and rosacea-prone skin.", "price" => "30", "skintype_id" => combo.id, "review_count" => "30", "rating" => "4.4", "link" => "http://www.sephora.com/mineral-cr-me-broad-spectrum-spf-50-uva-uvb-sunscreen-P383591?skuId=1574219", "image" => "http://www.sephora.com/productimages/sku/s1574219-main-hero.jpg")
Product.create("brand_id" => shiseido.id, "product_type_id" => facesunscreen.id, "name" => "Sun Protection Eye Cream Broad Spectrum SPF 34 Sunscreen", "description" => "An eye cream to hydrate, prevent the appearance of wrinkles, and protect against UVA/UVB rays.", "price" => "35.5", "skintype_id" => combo.id, "review_count" => "4", "rating" => "4.1", "link" => "http://www.sephora.com/sun-protection-eye-cream-broad-spectrum-spf-34-sunscreen-P384788?skuId=1507557", "image" => "http://www.sephora.com/productimages/sku/s1507557-main-hero.jpg")
Product.create("brand_id" => clinique.id, "product_type_id" => facesunscreen.id, "name" => "City Block Sheer Oil-Free Daily Face Protector SPF 25", "description" => "A lightweight daily sunscreen that provides UVA/UVB sun protection.", "price" => "22", "skintype_id" => combo.id, "review_count" => "360", "rating" => "4", "link" => "http://www.sephora.com/city-block-sheer-oil-free-daily-face-protector-spf-25-P196542?skuId=999565", "image" => "http://www.sephora.com/productimages/sku/s999565-main-hero.jpg")

ProductRating.delete_all
ProductRating.create("user_id" => "1", "product_id" => korresm.id, "currently_use" => "1", "works" => "1", "oily" => "0", "dry" => "0", "heavy" => "0", "breakout" => "0", "allergic" => "0", "treats" => "1", "review" => "Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.", "rating" => "4")
ProductRating.create("user_id" => "1", "product_id" => glamglowm.id, "currently_use" => "0", "works" => "1", "oily" => "0", "dry" => "1", "heavy" => "0", "breakout" => "0", "allergic" => "0", "treats" => "0", "review" => "Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.", "rating" => "2")
ProductRating.create("user_id" => "1", "product_id" => originsm.id, "currently_use" => "1", "works" => "0", "oily" => "1", "dry" => "1", "heavy" => "0", "breakout" => "0", "allergic" => "0", "treats" => "0", "review" => "Maecenas sed diam eget risus varius blandit sit amet non magna.", "rating" => "3")
ProductRating.create("user_id" => "1", "product_id" => cliniquem.id, "currently_use" => "0", "works" => "0", "oily" => "0", "dry" => "1", "heavy" => "1", "breakout" => "1", "allergic" => "0", "treats" => "0", "review" => "Donec id elit non mi porta gravida at eget metus. Maecenas faucibus mollis interdum.", "rating" => "1")
ProductRating.create("user_id" => "1", "product_id" => shiseidom.id, "currently_use" => "1", "works" => "1", "oily" => "1", "dry" => "0", "heavy" => "0", "breakout" => "0", "allergic" => "0", "treats" => "0", "review" => "Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras mattis consectetur purus sit amet fermentum.", "rating" => "5")
ProductRating.create("user_id" => "1", "product_id" => freshm.id, "currently_use" => "0", "works" => "0", "oily" => "0", "dry" => "0", "heavy" => "1", "breakout" => "1", "allergic" => "1", "treats" => "0", "review" => "Maecenas sed diam eget risus varius blandit sit amet non magna.", "rating" => "2")
